const WORDS={um:1,uma:1,dois:2,duas:2,tres:3,quatro:4,cinco:5,seis:6,sete:7,oito:8,nove:9,dez:10,onze:11,doze:12,treze:13,quatorze:14,quinze:15,dezesseis:16,dezessete:17,dezoito:18,dezenove:19,vinte:20}
const norm=value=>String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')
const number=value=>Number(value)||WORDS[norm(value)]||0
export function interpretFieldVoice(transcript,activities=[]){
  const text=String(transcript||'').trim(),low=norm(text),roles={}
  for(const role of ['pedreiro','pedreiros','ajudante','ajudantes','servente','serventes','carpinteiro','carpinteiros','armador','armadores','eletricista','eletricistas','encanador','encanadores']){const match=low.match(new RegExp(`(\\d+|${Object.keys(WORDS).join('|')})\\s+${role}\\b`));if(match){const key=role.replace(/s$/,'').replace('pedreiro','Pedreiro').replace('ajudante','Ajudante').replace('servente','Servente').replace('carpinteiro','Carpinteiro').replace('armador','Armador').replace('eletricista','Eletricista').replace('encanador','Encanador');roles[key]=(roles[key]||0)+number(match[1])}}
  const quantityMatch=low.match(/(\d+(?:[.,]\d+)?)\s*(m2|m²|metros? quadrados?|m3|m³|metros? cubicos?|unidades?|un\b|metros?\b)/),quantity=quantityMatch?Number(quantityMatch[1].replace(',','.')):null
  let unit=quantityMatch?.[2]||'';if(/m2|quadrad/.test(unit))unit='m²';else if(/m3|cubic/.test(unit))unit='m³';else if(/un/.test(unit))unit='un.';else if(unit)unit='m'
  const downtime=low.match(/(\d+(?:[.,]\d+)?|uma|duas|tres|quatro|cinco|seis|sete|oito)\s*horas?\s*(?:parad[oa]s?|de parada)/),absence=[...text.matchAll(/\b([A-ZÁÉÍÓÚÂÊÔÃÕÇ][a-záéíóúâêôãõç]+)\s+(?:faltou|não veio)/g)].map(match=>match[1])
  const tokens=low.match(/[a-z0-9]+/g)?.filter(word=>word.length>3)||[],scored=activities.map(activity=>({activity,score:tokens.filter(word=>norm(activity.title).includes(word)).length})).sort((a,b)=>b.score-a.score),activity=scored[0]?.score?scored[0].activity:null
  let occurrence=null;if(/argamassa.*nao chegou|material.*nao chegou|falta de material/.test(low))occurrence={occurrenceType:'falta_material',title:'Falta de material'};else if(/chuv/.test(low))occurrence={occurrenceType:'chuva',title:'Interferência por chuva'};else if(absence.length)occurrence={occurrenceType:'falta_trabalhador',title:'Ausência de trabalhador'}
  const workerCount=Object.values(roles).reduce((sum,value)=>sum+value,0),reason=text.match(/(?:porque|pois|devido a|devido à)\s+(.+?)(?:\.|$)/i)?.[1]||''
  return {transcript:text,report:{reportDate:new Date().toISOString().slice(0,10),weather:/chuv/.test(low)?'Chuva mencionada no relato':'',notes:text},production:{activityId:activity?.id||null,activityTitle:activity?.title||'',quantity,unit:unit||activity?.unit||'',workedHours:8,workerCount,downtimeHours:downtime?number(downtime[1]):0,downtimeReason:reason},workforce:{roles,absences:absence},occurrence:occurrence?{...occurrence,activityId:activity?.id||null,description:reason||text}:null,confidence:activity||quantity||workerCount?0.72:0.35,mode:'structured-fallback',requiresConfirmation:true}
}
