import crypto from 'crypto'
import jwt from 'jsonwebtoken'
import {parseCookies} from './http-safety.mjs'
function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length),'Cache-Control':'no-store'});res.end(data)}
async function json(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>5*1024*1024)return null;chunks.push(c)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}catch{return null}}
const date=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))?String(value):null
export function createGovernanceRoutes({pool,jwtSecret,cookieName='obra360_session'}){
 async function user(req){const token=parseCookies(req.headers.cookie||'')[cookieName];if(!token)return null;try{const p=jwt.verify(token,jwtSecret);return(await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[p.id])).rows[0]||null}catch{return null}}
 async function ctx(person,projectId){if(!person)return null;const q=await pool.query(`SELECT p.company_id FROM projects p LEFT JOIN company_users cu ON cu.company_id=p.company_id AND cu.user_id=$2 AND cu.is_active=true LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=$2 WHERE p.id=$1 AND ($3='admin' OR ($3='team' AND cu.user_id IS NOT NULL AND cu.role<>'client') OR pm.user_id IS NOT NULL)`,[projectId,person.id,person.role]);return q.rows[0]||null}
 const staff=p=>['admin','team'].includes(p?.role)
 async function event(projectId,userId,type,title,description){await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,$2,$3,$4,$5)`,[projectId,type,title,description,userId])}
 return async function handle(req,res,url){const safety=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/safety\/?$/),requirement=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/safety-requirements\/?$/),assignment=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/activities\/(\d+)\/safety(?:\/(\d+))?\/?$/),documents=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/documents\/?$/),version=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/documents\/(\d+)\/versions\/?$/);if(!safety&&!requirement&&!assignment&&!documents&&!version)return false;const projectId=Number((safety||requirement||assignment||documents||version)[1]),person=await user(req),context=await ctx(person,projectId);if(!person){send(res,401,{error:'Não autenticado'});return true}if(!context){send(res,403,{error:'Sem acesso'});return true}
  if(safety&&req.method==='GET'){const [items,catalog,activities]=await Promise.all([pool.query(`SELECT ar.*,r.code,r.title,r.description,r.requirement_type,t.title activity_title,t.wbs_code,u.name verified_by_name FROM activity_safety_requirements ar JOIN safety_requirements r ON r.id=ar.requirement_id JOIN os_tasks t ON t.id=ar.activity_id LEFT JOIN users u ON u.id=ar.verified_by WHERE t.project_id=$1 ORDER BY (ar.status='pending') DESC,t.task_order,r.title`,[projectId]),pool.query('SELECT * FROM safety_requirements WHERE company_id=$1 AND active=true ORDER BY title',[context.company_id]),pool.query(`SELECT id,title,wbs_code FROM os_tasks WHERE project_id=$1 AND status<>'na' ORDER BY task_order,id`,[projectId])]);send(res,200,{items:items.rows,catalog:catalog.rows,activities:activities.rows,summary:{pending:items.rows.filter(x=>x.status==='pending').length,verified:items.rows.filter(x=>x.status==='verified').length}});return true}
  if(documents&&req.method==='GET'){const q=await pool.query(`SELECT d.*,t.title activity_title,u.name responsible_name,COALESCE(json_agg(json_build_object('id',v.id,'version_number',v.version_number,'file_name',v.file_name,'file_url',v.file_url,'mime_type',v.mime_type,'file_size',v.file_size,'notes',v.notes,'created_at',v.created_at) ORDER BY v.version_number DESC) FILTER(WHERE v.id IS NOT NULL),'[]') versions FROM documents d LEFT JOIN os_tasks t ON t.id=d.activity_id LEFT JOIN users u ON u.id=d.responsible_user_id LEFT JOIN document_versions v ON v.document_id=d.id WHERE d.project_id=$1 GROUP BY d.id,t.title,u.name ORDER BY d.updated_at DESC`,[projectId]);const a=await pool.query(`SELECT id,title,wbs_code FROM os_tasks WHERE project_id=$1 AND status<>'na' ORDER BY task_order,id`,[projectId]);send(res,200,{documents:q.rows,activities:a.rows});return true}
  if(!staff(person)){send(res,403,{error:'Somente a equipe técnica pode alterar estes registros.'});return true}const body=await json(req);if(!body){send(res,400,{error:'Dados inválidos ou arquivo acima de 5 MB.'});return true}
  if(requirement&&req.method==='POST'){const title=String(body.title||'').trim().slice(0,180);if(!title){send(res,400,{error:'Informe o requisito.'});return true}const q=await pool.query(`INSERT INTO safety_requirements(company_id,code,title,description,requirement_type) VALUES($1,$2,$3,$4,$5) ON CONFLICT(company_id,code) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,requirement_type=EXCLUDED.requirement_type,active=true RETURNING *`,[context.company_id,String(body.code||'').trim().slice(0,40)||null,title,String(body.description||'').trim().slice(0,1000)||null,String(body.requirementType||'control').slice(0,60)]);send(res,201,{requirement:q.rows[0]});return true}
  if(assignment&&req.method==='POST'&&!assignment[3]){const requirementId=Number(body.requirementId),activityId=Number(assignment[2]);const valid=await pool.query(`SELECT 1 FROM os_tasks t JOIN projects p ON p.id=t.project_id JOIN safety_requirements r ON r.company_id=p.company_id WHERE t.id=$1 AND t.project_id=$2 AND r.id=$3`,[activityId,projectId,requirementId]);if(!valid.rowCount){send(res,400,{error:'Atividade ou requisito inválido.'});return true}await pool.query(`INSERT INTO activity_safety_requirements(activity_id,requirement_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[activityId,requirementId]);await event(projectId,person.id,'safety','Requisito de SST vinculado','A atividade permanece pendente até revisão do profissional responsável.');send(res,201,{ok:true});return true}
  if(assignment&&req.method==='PATCH'&&assignment[3]){const status=['pending','verified','not_applicable'].includes(body.status)?body.status:'pending',q=await pool.query(`UPDATE activity_safety_requirements ar SET status=$1,verified_by=CASE WHEN $1='pending' THEN NULL ELSE $2 END,verified_at=CASE WHEN $1='pending' THEN NULL ELSE now() END,evidence_note=$3 FROM os_tasks t WHERE ar.activity_id=t.id AND t.project_id=$4 AND ar.activity_id=$5 AND ar.requirement_id=$6 RETURNING ar.*`,[status,person.id,String(body.evidenceNote||'').trim().slice(0,1200)||null,projectId,Number(assignment[2]),Number(assignment[3])]);if(!q.rowCount){send(res,404,{error:'Vínculo não encontrado.'});return true}await event(projectId,person.id,'safety','Revisão de requisito de SST',`Status: ${status}. Não representa liberação legal automática.`);send(res,200,{item:q.rows[0]});return true}
  if(documents&&req.method==='POST'){const title=String(body.title||'').trim().slice(0,180),type=String(body.documentType||'').trim().slice(0,80);if(!title||!type){send(res,400,{error:'Informe título e tipo.'});return true}const activityId=Number(body.activityId)||null;if(activityId&&!(await pool.query('SELECT 1 FROM os_tasks WHERE id=$1 AND project_id=$2',[activityId,projectId])).rowCount){send(res,400,{error:'Atividade inválida.'});return true}const q=await pool.query(`INSERT INTO documents(company_id,project_id,activity_id,document_type,number,title,valid_from,valid_until,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[context.company_id,projectId,activityId,type,String(body.number||'').trim().slice(0,80)||null,title,date(body.validFrom),date(body.validUntil),String(body.status||'draft').slice(0,40),person.id]);await event(projectId,person.id,'document','Documento cadastrado',title);send(res,201,{document:q.rows[0]});return true}
  if(version&&req.method==='POST'){const documentId=Number(version[2]),file=String(body.fileUrl||''),name=String(body.fileName||'').trim().slice(0,240);if(!name||!file){send(res,400,{error:'Selecione o arquivo.'});return true}if(Number(body.fileSize)>3*1024*1024){send(res,413,{error:'O arquivo deve ter no máximo 3 MB nesta fase.'});return true}const doc=await pool.query('SELECT * FROM documents WHERE id=$1 AND project_id=$2 AND company_id=$3',[documentId,projectId,context.company_id]);if(!doc.rowCount){send(res,404,{error:'Documento não encontrado.'});return true}const next=await pool.query('SELECT COALESCE(MAX(version_number),0)+1 version FROM document_versions WHERE document_id=$1',[documentId]),checksum=crypto.createHash('sha256').update(file).digest('hex'),q=await pool.query(`INSERT INTO document_versions(document_id,version_number,file_name,file_url,checksum,notes,uploaded_by,mime_type,file_size) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[documentId,next.rows[0].version,name,file,checksum,String(body.notes||'').trim().slice(0,500)||null,person.id,String(body.mimeType||'').slice(0,100)||null,Number(body.fileSize)||null]);await pool.query('UPDATE documents SET updated_at=now() WHERE id=$1',[documentId]);await event(projectId,person.id,'document',`Nova versão: ${doc.rows[0].title}`,`Versão ${next.rows[0].version} · ${name}`);send(res,201,{version:q.rows[0]});return true}
  send(res,405,{error:'Método não permitido'});return true}
 }
