import jwt from 'jsonwebtoken'
import {parseCookies} from './http-safety.mjs'
import {criticalPath} from './motor-engine.mjs'

function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length),'Cache-Control':'no-store'});res.end(data)}
async function json(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>128*1024)return null;chunks.push(chunk)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}catch{return null}}
const day=value=>value?String(value).slice(0,10):null
const lower=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
const questionLike=text=>/\?$/.test(text)||/^(o que|qual|quais|como|quando|por que|porque|tem|temos|ha|há|estamos|quanto|quantos|minha|meu|existe|preciso|posso)\b/.test(lower(text).trim())

export function createIntelligenceRoutes({pool,jwtSecret,cookieName='obra360_session',geminiApiKey}){
  async function user(req){const token=parseCookies(req.headers.cookie||'')[cookieName];if(!token)return null;try{const p=jwt.verify(token,jwtSecret);return(await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[p.id])).rows[0]||null}catch{return null}}
  async function access(person,projectId){if(!person)return false;if(person.role==='admin')return true;return(await pool.query(`SELECT 1 FROM projects p LEFT JOIN company_users cu ON cu.company_id=p.company_id AND cu.user_id=$2 AND cu.is_active=true LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=$2 WHERE p.id=$1 AND (($3='team' AND cu.user_id IS NOT NULL AND cu.role<>'client') OR pm.user_id IS NOT NULL)`,[projectId,person.id,person.role])).rowCount>0}
  async function context(projectId){
    const [project,tasks,blockers,dependencies,rdos,records,safety,documents,costs,municipal,allocations]=await Promise.all([
      pool.query('SELECT id,name,status,budget,spent,committed,city FROM projects WHERE id=$1',[projectId]),
      pool.query(`SELECT id,wbs_code,title,status,priority,planned_start,planned_end,duration_days,actual_start,actual_end,percent_complete,planned_quantity,actual_quantity,unit,delay_reason FROM os_tasks WHERE project_id=$1 AND status<>'na' ORDER BY task_order,id`,[projectId]),
      pool.query(`SELECT b.id,b.blocker_type,b.title,b.description,b.due_date,t.title activity_title FROM blockers b JOIN os_tasks t ON t.id=b.activity_id WHERE b.project_id=$1 AND b.status='active' ORDER BY b.due_date NULLS LAST,b.id`,[projectId]),
      pool.query(`SELECT d.predecessor_id,d.successor_id,p.title predecessor,s.title successor,d.dependency_type,d.lag_days,p.status predecessor_status FROM activity_dependencies d JOIN os_tasks p ON p.id=d.predecessor_id JOIN os_tasks s ON s.id=d.successor_id WHERE d.project_id=$1`,[projectId]),
      pool.query(`SELECT report_date,weather,notes,status FROM daily_reports WHERE project_id=$1 ORDER BY report_date DESC LIMIT 14`,[projectId]),
      pool.query(`SELECT p.record_date,p.quantity,p.unit,p.worker_count,p.worked_hours,p.downtime_hours,p.downtime_reason,t.title activity_title FROM productivity_records p JOIN os_tasks t ON t.id=p.activity_id WHERE p.project_id=$1 ORDER BY p.record_date DESC,p.id DESC LIMIT 30`,[projectId]),
      pool.query(`SELECT ar.status,r.title,t.title activity_title FROM activity_safety_requirements ar JOIN safety_requirements r ON r.id=ar.requirement_id JOIN os_tasks t ON t.id=ar.activity_id WHERE t.project_id=$1 ORDER BY t.task_order,r.title`,[projectId]),
      pool.query(`SELECT id,title,document_type,number,status,valid_until FROM documents WHERE project_id=$1 ORDER BY updated_at DESC LIMIT 50`,[projectId]),
      pool.query(`SELECT status,COALESCE(SUM(amount),0) total FROM os_cost_entries WHERE project_id=$1 GROUP BY status`,[projectId]),
      pool.query(`SELECT ps.status,ps.protocol_number,ps.notes,s.title FROM project_administrative_steps ps JOIN municipal_workflow_steps s ON s.id=ps.workflow_step_id WHERE ps.project_id=$1 ORDER BY s.order_index`,[projectId]),
      pool.query(`SELECT a.start_date,a.end_date,COALESCE(t.name,w.name,'Recurso') resource_name,ot.title activity_title FROM allocations a LEFT JOIN teams t ON t.id=a.team_id LEFT JOIN workers w ON w.id=a.worker_id LEFT JOIN os_tasks ot ON ot.id=a.activity_id WHERE a.project_id=$1 AND a.end_date>=CURRENT_DATE ORDER BY a.start_date LIMIT 40`,[projectId]),
    ])
    return {project:project.rows[0],tasks:tasks.rows,blockers:blockers.rows,dependencies:dependencies.rows,rdos:rdos.rows,records:records.rows,safety:safety.rows,documents:documents.rows,costs:costs.rows,municipal:municipal.rows,allocations:allocations.rows}
  }
  function grounded(question,c){
    const q=lower(question),today=new Date().toISOString().slice(0,10),facts=[],sources=[],inferences=[]
    const source=(label,recordId)=>sources.push({label,...(recordId?{recordId}: {})})
    const pending=c.tasks.filter(x=>x.status!=='done'),late=pending.filter(x=>x.planned_end&&day(x.planned_end)<today),blocked=c.blockers,openSafety=c.safety.filter(x=>x.status==='pending'),paid=Number(c.costs.find(x=>x.status==='paid')?.total||0),committed=Number(c.costs.find(x=>x.status==='committed')?.total||0)
    const next=pending.filter(x=>!blocked.some(b=>b.activity_title===x.title)&&!c.dependencies.some(d=>Number(d.successor_id)===Number(x.id)&&d.predecessor_status!=='done')).sort((a,b)=>(a.planned_start||'9999').localeCompare(b.planned_start||'9999'))[0]
    let answer=''
    if(/caminho critico/.test(q)){const path=criticalPath(c.tasks,c.dependencies),critical=c.tasks.filter(x=>path.activities[x.id]?.critical);facts.push(`${critical.length} atividade(s) no caminho crítico calculado com dependências término-início.`);critical.slice(0,8).forEach(x=>source(`Atividade crítica: ${x.title}`,x.id));answer=critical.length?`O caminho crítico calculado inclui: ${critical.slice(0,8).map(x=>x.title).join(', ')}. Dependências diferentes de término-início exigem revisão no planejamento.`:'Não há dados de duração e dependências suficientes para calcular o caminho crítico.'}
    else if(/atras|prazo|cronograma/.test(q)){facts.push(`${late.length} atividade(s) com fim planejado anterior a hoje e ainda não concluída(s).`);late.slice(0,5).forEach(x=>source(`Atividade: ${x.title}`,x.id));answer=late.length?`Há ${late.length} atividade(s) potencialmente atrasada(s): ${late.slice(0,3).map(x=>x.title).join(', ')}. O impacto nas sucessoras deve ser validado no planejamento.`:'Não encontrei atividades vencidas entre as datas planejadas registradas.'}
    else if(/bloque|imped|concretagem/.test(q)){facts.push(`${blocked.length} bloqueio(s) ativo(s).`);blocked.slice(0,6).forEach(x=>source(`Bloqueio: ${x.activity_title} — ${x.title}`,x.id));answer=blocked.length?`Os bloqueios ativos são: ${blocked.slice(0,5).map(x=>`${x.activity_title}: ${x.title}`).join('; ')}.`:'Não há bloqueios ativos registrados. Isso não comprova que a frente esteja tecnicamente liberada.'}
    else if(/sst|seguranca|segurança|risco/.test(q)){facts.push(`${openSafety.length} requisito(s) de SST pendente(s).`);openSafety.slice(0,6).forEach(x=>source(`SST: ${x.activity_title} — ${x.title}`));answer=openSafety.length?`Existem ${openSafety.length} pendência(s) de SST registrada(s): ${openSafety.slice(0,5).map(x=>`${x.activity_title}: ${x.title}`).join('; ')}. A avaliação e liberação permanecem com o profissional habilitado.`:'Não encontrei requisitos de SST com status pendente. Isso não equivale a declarar conformidade ou liberar a atividade.'}
    else if(/art|rrt|alvara|alvará|document/.test(q)){const matches=c.documents.filter(x=>!(/art/.test(q))||/art/.test(lower(`${x.document_type} ${x.title}`)));facts.push(`${matches.length} documento(s) correspondente(s) registrado(s).`);matches.slice(0,6).forEach(x=>source(`Documento: ${x.title} — ${x.status}`,x.id));answer=matches.length?matches.slice(0,5).map(x=>`${x.title}: ${x.status}${x.valid_until?` (validade ${day(x.valid_until)})`:''}`).join('; '):'Não encontrei documento correspondente nos registros desta obra.'}
    else if(/prefeitura|municip|protocolo|licenca|licença/.test(q)){const open=c.municipal.filter(x=>!['approved','not_applicable'].includes(x.status));facts.push(`${open.length} etapa(s) administrativa(s) em aberto.`);open.slice(0,6).forEach(x=>source(`Fluxo municipal: ${x.title} — ${x.status}`));answer=open.length?`No fluxo administrativo ainda constam: ${open.slice(0,5).map(x=>`${x.title} (${x.status})`).join('; ')}.`:'Não há etapa municipal aberta registrada. Consulte a fonte oficial antes de interpretar isso como regularização concluída.'}
    else if(/gasto|custo|finance|orcamento|orçamento/.test(q)){facts.push(`Custo realizado registrado: R$ ${paid.toLocaleString('pt-BR',{minimumFractionDigits:2})}.`,`Valor comprometido: R$ ${committed.toLocaleString('pt-BR',{minimumFractionDigits:2})}.`);source('Lançamentos financeiros da obra');answer=`Foram registrados R$ ${paid.toLocaleString('pt-BR',{minimumFractionDigits:2})} como realizados e R$ ${committed.toLocaleString('pt-BR',{minimumFractionDigits:2})} como comprometidos.`}
    else if(/equipe|mao de obra|mão de obra|capacidade|profission/.test(q)){facts.push(`${c.allocations.length} alocação(ões) vigente(s) ou futura(s) registrada(s).`);c.allocations.slice(0,6).forEach(x=>source(`Alocação: ${x.resource_name} — ${x.activity_title||'sem atividade'}`));answer=c.allocations.length?`Há ${c.allocations.length} alocação(ões) vigente(s) ou futura(s). A suficiência depende das quantidades, produtividade e prazo cadastrados na visão de capacidade.`:'Não encontrei alocações vigentes ou futuras. Não há dados suficientes para afirmar que a equipe será suficiente.'}
    else if(/amanha|amanhã|proxima acao|próxima ação|agora|depois/.test(q)){if(next){facts.push(`Próxima atividade não concluída e sem bloqueio formal: ${next.title}.`);source(`Atividade: ${next.title}`,next.id);answer=`A próxima ação sugerida é revisar e encaminhar “${next.title}”. Confirme no campo se não há impedimentos ainda não registrados.`}else answer='Não encontrei uma atividade pendente sem bloqueio formal. Revise bloqueios e datas do planejamento.'}
    else {const progress=c.tasks.length?Math.round(c.tasks.reduce((s,x)=>s+Number(x.percent_complete||0),0)/c.tasks.length):0;facts.push(`Progresso médio informado: ${progress}%.`,`${c.tasks.length-pending.length} de ${c.tasks.length} atividades concluídas.`,`${blocked.length} bloqueio(s) ativo(s).`);source('Planejamento e status das atividades');source('Bloqueios ativos');answer=`A obra registra progresso médio de ${progress}%, ${c.tasks.length-pending.length} de ${c.tasks.length} atividades concluídas e ${blocked.length} bloqueio(s) ativo(s).${next?` Próxima ação sugerida: ${next.title}.`:''}`}
    if(!facts.length)inferences.push('Não há dados suficientes para uma conclusão específica.')
    return {answer,facts,inferences,sources,insufficientData:!facts.length}
  }
  return async function handle(req,res,url){const match=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/intelligence\/ask\/?$/);if(!match)return false;const projectId=Number(match[1]),person=await user(req);if(!person){send(res,401,{error:'Não autenticado'});return true}if(!(await access(person,projectId))){send(res,403,{error:'Sem acesso'});return true}if(req.method!=='POST'){send(res,405,{error:'Método não permitido'});return true}const body=await json(req),question=String(body?.question||'').trim().slice(0,2000);if(!question){send(res,400,{error:'Faça uma pergunta sobre a obra.'});return true}if(!questionLike(question)){send(res,200,{handled:false});return true}const c=await context(projectId);if(!c.project){send(res,404,{error:'Obra não encontrada'});return true}let result=grounded(question,c)
    if(geminiApiKey){try{const compact={project:c.project,tasks:c.tasks.slice(0,80),blockers:c.blockers,safety:c.safety,documents:c.documents,municipal:c.municipal,records:c.records.slice(0,15),rdos:c.rdos.slice(0,8),costs:c.costs,allocations:c.allocations};const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiApiKey},body:JSON.stringify({contents:[{parts:[{text:`Você é o Agente da Obra VIÇO. Responda somente com os DADOS fornecidos. Diferencie fatos de inferências. Se faltar dado, diga claramente. Nunca declare liberação técnica, conformidade legal ou decisão automática. Retorne JSON {answer,facts:string[],inferences:string[],sourceLabels:string[],insufficientData:boolean}. PERGUNTA: ${question}\nDADOS: ${JSON.stringify(compact)}`}]}],generationConfig:{temperature:0.05,maxOutputTokens:900,responseMimeType:'application/json'}})});if(response.ok){const data=await response.json(),raw=data?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'',parsed=JSON.parse(raw);if(parsed?.answer)result={...result,answer:String(parsed.answer)}}}catch(error){console.error('intelligence-grounding',error)}}
    send(res,200,{handled:true,analysis:{summary:result.answer,answer:result.answer,action:'query',suggestions:[],safety:[],mode:geminiApiKey?'grounded-ai':'grounded-rules',...result}});return true}
}
