import jwt from 'jsonwebtoken'
import {parseCookies} from './http-safety.mjs'
function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length),'Cache-Control':'no-store'});res.end(data)}
async function json(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>256*1024)return null;chunks.push(c)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}catch{return null}}
export function createMunicipalRoutes({pool,jwtSecret,cookieName='obra360_session'}){
 async function user(req){const token=parseCookies(req.headers.cookie||'')[cookieName];if(!token)return null;try{const p=jwt.verify(token,jwtSecret);return(await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[p.id])).rows[0]||null}catch{return null}}
 async function context(person,projectId){if(!person)return null;const q=await pool.query(`SELECT p.company_id,p.city,op.profile->>'kind' project_kind FROM projects p LEFT JOIN os_profiles op ON op.project_id=p.id LEFT JOIN company_users cu ON cu.company_id=p.company_id AND cu.user_id=$2 AND cu.is_active=true LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=$2 WHERE p.id=$1 AND ($3='admin' OR ($3='team' AND cu.user_id IS NOT NULL AND cu.role<>'client') OR pm.user_id IS NOT NULL)`,[projectId,person.id,person.role]);return q.rows[0]||null}
 const staff=p=>['admin','team'].includes(p?.role)
 return async function handle(req,res,url){const base=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/municipal\/?$/),workflow=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/municipal\/workflows\/?$/),apply=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/municipal\/apply\/?$/),step=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/municipal\/steps\/(\d+)\/?$/);if(!base&&!workflow&&!apply&&!step)return false;const projectId=Number((base||workflow||apply||step)[1]),person=await user(req),ctx=await context(person,projectId);if(!person){send(res,401,{error:'Não autenticado'});return true}if(!ctx){send(res,403,{error:'Sem acesso'});return true}
  if(base&&req.method==='GET'){const [templates,steps]=await Promise.all([pool.query(`SELECT w.*,COUNT(s.id)::int step_count FROM municipal_workflows w LEFT JOIN municipal_workflow_steps s ON s.workflow_id=w.id WHERE w.company_id=$1 AND w.active=true GROUP BY w.id ORDER BY w.municipality,w.name`,[ctx.company_id]),pool.query(`SELECT ps.*,s.code,s.title,s.description,s.order_index,s.requires_document_type,w.name workflow_name,w.municipality,w.state_code,u.name responsible_name FROM project_administrative_steps ps JOIN municipal_workflow_steps s ON s.id=ps.workflow_step_id JOIN municipal_workflows w ON w.id=s.workflow_id LEFT JOIN users u ON u.id=ps.responsible_user_id WHERE ps.project_id=$1 ORDER BY s.order_index`,[projectId])]);send(res,200,{templates:templates.rows,steps:steps.rows,project:{city:ctx.city,kind:ctx.project_kind},summary:{total:steps.rowCount,approved:steps.rows.filter(x=>x.status==='approved').length,requirements:steps.rows.filter(x=>x.status==='requirement').length}});return true}
  if(!staff(person)){send(res,403,{error:'Somente a equipe pode configurar o fluxo municipal.'});return true}const body=await json(req);if(!body){send(res,400,{error:'Dados inválidos'});return true}
  if(workflow&&req.method==='POST'){const municipality=String(body.municipality||'').trim().slice(0,120),state=String(body.stateCode||'').trim().toUpperCase().slice(0,2),kind=String(body.projectKind||'').trim().slice(0,80),name=String(body.name||'').trim().slice(0,160),steps=Array.isArray(body.steps)?body.steps.map(x=>String(x).trim()).filter(Boolean).slice(0,40):[];if(!municipality||state.length!==2||!kind||!name||!steps.length){send(res,400,{error:'Informe município, UF, tipo, nome e ao menos uma etapa verificada.'});return true}const client=await pool.connect();try{await client.query('BEGIN');const w=await client.query(`INSERT INTO municipal_workflows(company_id,municipality,state_code,project_kind,name,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[ctx.company_id,municipality,state,kind,name,person.id]);for(let i=0;i<steps.length;i++)await client.query(`INSERT INTO municipal_workflow_steps(workflow_id,code,title,order_index) VALUES($1,$2,$3,$4)`,[w.rows[0].id,`ADM-${String(i+1).padStart(2,'0')}`,steps[i],i+1]);await client.query('COMMIT');send(res,201,{workflow:w.rows[0]})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}return true}
  if(apply&&req.method==='POST'){const workflowId=Number(body.workflowId),valid=await pool.query('SELECT 1 FROM municipal_workflows WHERE id=$1 AND company_id=$2 AND active=true',[workflowId,ctx.company_id]);if(!valid.rowCount){send(res,400,{error:'Fluxo inválido para esta empresa.'});return true}const q=await pool.query(`INSERT INTO project_administrative_steps(project_id,workflow_step_id) SELECT $1,id FROM municipal_workflow_steps WHERE workflow_id=$2 ON CONFLICT(project_id,workflow_step_id) DO NOTHING RETURNING id`,[projectId,workflowId]);await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'municipal','Fluxo administrativo aplicado',$2,$3)`,[projectId,`${q.rowCount} etapa(s) adicionadas. Requisitos devem ser confirmados pela fonte oficial.`,person.id]);send(res,201,{added:q.rowCount});return true}
  if(step&&req.method==='PATCH'){const status=['pending','in_progress','requirement','approved','not_applicable'].includes(body.status)?body.status:'pending',q=await pool.query(`UPDATE project_administrative_steps SET status=$1,protocol_number=$2,notes=$3,responsible_user_id=$4,started_at=CASE WHEN $1='in_progress' AND started_at IS NULL THEN now() ELSE started_at END,completed_at=CASE WHEN $1='approved' THEN now() ELSE NULL END,updated_at=now() WHERE id=$5 AND project_id=$6 RETURNING *`,[status,String(body.protocolNumber||'').trim().slice(0,100)||null,String(body.notes||'').trim().slice(0,1200)||null,person.id,Number(step[2]),projectId]);if(!q.rowCount){send(res,404,{error:'Etapa administrativa não encontrada.'});return true}send(res,200,{step:q.rows[0]});return true}
  send(res,405,{error:'Método não permitido'});return true
 }
}
