import jwt from 'jsonwebtoken'
import {parseCookies} from './http-safety.mjs'
function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length),'Cache-Control':'no-store'});res.end(data)}
async function json(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>128*1024)return null;chunks.push(c)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}catch{return null}}
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0)
const date=value=>new Date(value).toLocaleDateString('pt-BR')
export function createReportingRoutes({pool,jwtSecret,cookieName='obra360_session'}){
 async function user(req){const token=parseCookies(req.headers.cookie||'')[cookieName];if(!token)return null;try{const p=jwt.verify(token,jwtSecret);return(await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[p.id])).rows[0]||null}catch{return null}}
 async function access(person,projectId){if(!person)return false;if(person.role==='admin')return true;return(await pool.query(`SELECT 1 FROM projects p LEFT JOIN company_users cu ON cu.company_id=p.company_id AND cu.user_id=$2 AND cu.is_active=true LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=$2 WHERE p.id=$1 AND (($3='team' AND cu.user_id IS NOT NULL AND cu.role<>'client') OR pm.user_id IS NOT NULL)`,[projectId,person.id,person.role])).rowCount>0}
 return async function handle(req,res,url){const match=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/reports\/operational\/?$/);if(!match)return false;const projectId=Number(match[1]),person=await user(req);if(!person){send(res,401,{error:'Não autenticado'});return true}if(!(await access(person,projectId))){send(res,403,{error:'Sem acesso'});return true}
  if(req.method==='GET'){const q=await pool.query(`SELECT id,report_type,title,period_start,period_end,content,metrics,status,created_at FROM operational_reports WHERE project_id=$1 ORDER BY created_at DESC LIMIT 30`,[projectId]);send(res,200,{reports:q.rows});return true}
  if(req.method!=='POST'){send(res,405,{error:'Método não permitido'});return true}const body=await json(req),days=Math.max(1,Math.min(90,Number(body?.days)||7)),requested=['weekly','client','technical','safety','executive'].includes(String(body?.type))?String(body.type):'weekly',type=['admin','team'].includes(person.role)?requested:'client',end=new Date(),start=new Date(end);start.setUTCDate(start.getUTCDate()-days+1);const startDate=start.toISOString().slice(0,10),endDate=end.toISOString().slice(0,10)
  const [project,tasks,records,reports,occurrences,blockers,safety,documents,costs]=await Promise.all([pool.query('SELECT * FROM projects WHERE id=$1',[projectId]),pool.query(`SELECT id,title,status,planned_start,planned_end,planned_quantity,actual_quantity,unit,percent_complete,planned_cost,actual_cost FROM os_tasks WHERE project_id=$1 AND status<>'na' ORDER BY task_order,id`,[projectId]),pool.query(`SELECT p.*,t.title activity_title FROM productivity_records p JOIN os_tasks t ON t.id=p.activity_id WHERE p.project_id=$1 AND p.record_date BETWEEN $2 AND $3 ORDER BY p.record_date`,[projectId,startDate,endDate]),pool.query(`SELECT * FROM daily_reports WHERE project_id=$1 AND report_date BETWEEN $2 AND $3 ORDER BY report_date`,[projectId,startDate,endDate]),pool.query(`SELECT o.*,t.title activity_title FROM occurrences o LEFT JOIN os_tasks t ON t.id=o.activity_id WHERE o.project_id=$1 AND o.created_at::date BETWEEN $2 AND $3 ORDER BY o.created_at`,[projectId,startDate,endDate]),pool.query(`SELECT b.*,t.title activity_title FROM blockers b JOIN os_tasks t ON t.id=b.activity_id WHERE b.project_id=$1 AND b.status='active' ORDER BY b.created_at`,[projectId]),pool.query(`SELECT ar.status,r.title,t.title activity_title FROM activity_safety_requirements ar JOIN safety_requirements r ON r.id=ar.requirement_id JOIN os_tasks t ON t.id=ar.activity_id WHERE t.project_id=$1`,[projectId]),pool.query(`SELECT title,document_type,status,valid_until FROM documents WHERE project_id=$1 ORDER BY updated_at DESC`,[projectId]),pool.query(`SELECT status,amount FROM os_cost_entries WHERE project_id=$1`,[projectId])]);if(!project.rowCount){send(res,404,{error:'Obra não encontrada'});return true}
  const p=project.rows[0],planned=tasks.rows.reduce((s,x)=>s+Number(x.planned_quantity||0),0),actual=tasks.rows.reduce((s,x)=>s+Number(x.actual_quantity||0),0),physical=planned>0?Math.round(actual/planned*1000)/10:null,paid=costs.rows.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0),committed=costs.rows.filter(x=>x.status==='committed').reduce((s,x)=>s+Number(x.amount||0),0),pendingSafety=safety.rows.filter(x=>x.status==='pending'),expiredDocs=documents.rows.filter(x=>x.valid_until&&String(x.valid_until).slice(0,10)<endDate),done=tasks.rows.filter(x=>x.status==='done').length
  const metrics={physicalProgress:physical,checklistDone:done,checklistTotal:tasks.rowCount,productionRecords:records.rowCount,confirmedRdos:reports.rows.filter(x=>x.status==='confirmed').length,occurrences:occurrences.rowCount,activeBlockers:blockers.rowCount,pendingSafety:pendingSafety.length,expiredDocuments:expiredDocs.length,paid,committed}
  const title=type==='client'?'Resumo da sua obra':type==='safety'?'Relatório de SST':type==='executive'?'Relatório executivo':'Relatório operacional da obra',lines=[title,`Obra: ${p.name}`,`Período: ${date(start)} a ${date(end)}`,'','RESUMO EXECUTIVO',physical===null?'Avanço físico: sem quantidades suficientes para calcular.':`Avanço físico por quantidade: ${physical}%.`,`Atividades concluídas: ${done} de ${tasks.rowCount}.`,`RDOs confirmados no período: ${metrics.confirmedRdos}.`,`Bloqueios ativos: ${blockers.rowCount}.`,'','EXECUTADO NO PERÍODO',...(records.rows.length?records.rows.map(x=>`• ${x.activity_title}: ${x.quantity} ${x.unit} em ${date(x.record_date)}.`):['• Nenhum apontamento de produção no período.']),'','PRÓXIMOS MARCOS',...(tasks.rows.filter(x=>x.status!=='done'&&x.planned_start).slice(0,8).map(x=>`• ${x.title}: ${String(x.planned_start).slice(0,10)} a ${String(x.planned_end||'').slice(0,10)}.`)),'','BLOQUEIOS E OCORRÊNCIAS',...(blockers.rows.map(x=>`• Bloqueio — ${x.activity_title}: ${x.title}.`)),...(occurrences.rows.map(x=>`• ${x.title}${x.activity_title?` — ${x.activity_title}`:''}.`)),...(blockers.rowCount||occurrences.rowCount?[]:['• Nenhum registro no período.']),'','CUSTOS REGISTRADOS',`Realizado: ${money(paid)}. Comprometido: ${money(committed)}.`,'','SST E DOCUMENTOS',`Pendências de SST registradas: ${pendingSafety.length}.`,`Documentos vencidos registrados: ${expiredDocs.length}.`,'','DECISÕES E RESSALVAS','Este relatório consolida apenas dados registrados na VIÇO. Revise antes de compartilhar. Não representa aprovação técnica, conformidade legal ou liberação automática de atividade.']
  const content=lines.join('\n'),q=await pool.query(`INSERT INTO operational_reports(project_id,report_type,title,period_start,period_end,content,metrics,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,created_at`,[projectId,type,title,startDate,endDate,content,metrics,person.id]);await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'report',$2,$3,$4)`,[projectId,`Relatório gerado: ${title}`,`${startDate} a ${endDate}`,person.id]);send(res,201,{report:{id:q.rows[0].id,created_at:q.rows[0].created_at,title,content,metrics,periodLabel:`${date(start)} a ${date(end)}`,mode:'grounded'}});return true
 }
}
