import jwt from 'jsonwebtoken'
import {parseCookies} from './http-safety.mjs'
import {capacityRows,portfolioCapacity} from './capacity-engine.mjs'
function send(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':String(data.length),'Cache-Control':'no-store'});res.end(data)}
async function readJson(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>256*1024)return null;chunks.push(chunk)}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{}}catch{return null}}
const iso=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))?String(value):null
export function createWorkforceRoutes({pool,jwtSecret,cookieName='obra360_session'}){
 async function user(req){const token=parseCookies(req.headers.cookie||'')[cookieName];if(!token)return null;try{const payload=jwt.verify(token,jwtSecret);return (await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[payload.id])).rows[0]||null}catch{return null}}
 async function context(person,projectId){if(!person)return null;const q=await pool.query(`SELECT p.company_id FROM projects p LEFT JOIN company_users cu ON cu.company_id=p.company_id AND cu.user_id=$2 AND cu.is_active=true LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=$2 WHERE p.id=$1 AND ($3='admin' OR ($3='team' AND cu.user_id IS NOT NULL AND cu.role<>'client') OR pm.user_id IS NOT NULL)`,[projectId,person.id,person.role]);return q.rows[0]||null}
 const staff=person=>['admin','team'].includes(person?.role)
 async function event(projectId,userId,title,description){await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'workforce',$2,$3,$4)`,[projectId,title,description,userId])}
 return async function handleWorkforce(req,res,url){
  const base=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/workforce\/?$/),workers=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/workers\/?$/),teams=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/teams\/?$/),allocation=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/allocations\/?$/),activity=url.pathname.match(/^\/api\/vico\/projects\/(\d+)\/activities\/(\d+)\/workforce\/?$/)
  if(!base&&!workers&&!teams&&!allocation&&!activity)return false
  const projectId=Number((base||workers||teams||allocation||activity)[1]),person=await user(req),ctx=await context(person,projectId)
  if(!person){send(res,401,{error:'Não autenticado'});return true}if(!ctx){send(res,403,{error:'Sem acesso'});return true}
  if(base&&req.method==='GET'){if(!staff(person)){send(res,403,{error:'Capacidade e dados de trabalhadores são restritos à equipe.'});return true}const [activities,people,teamRows,allocations,portfolioTasks]=await Promise.all([pool.query(`SELECT id,title,wbs_code,status,planned_start,planned_end,planned_quantity,actual_quantity,unit,planned_productivity,workforce_trade FROM os_tasks WHERE project_id=$1 AND status<>'na' ORDER BY planned_start NULLS LAST,task_order,id`,[projectId]),pool.query(`SELECT * FROM workers WHERE company_id=$1 AND active=true ORDER BY trade NULLS LAST,name`,[ctx.company_id]),pool.query(`SELECT t.*,COUNT(tm.worker_id)::int member_count FROM teams t LEFT JOIN team_members tm ON tm.team_id=t.id AND tm.left_at IS NULL WHERE t.company_id=$1 AND t.active=true GROUP BY t.id ORDER BY t.name`,[ctx.company_id]),pool.query(`SELECT a.*,w.name worker_name,t.name team_name,ot.title activity_title FROM allocations a LEFT JOIN workers w ON w.id=a.worker_id LEFT JOIN teams t ON t.id=a.team_id LEFT JOIN os_tasks ot ON ot.id=a.activity_id WHERE a.project_id=$1 ORDER BY a.start_date,a.id`,[projectId]),pool.query(`SELECT t.id,t.project_id,p.name project_name,t.status,t.planned_start,t.planned_end,t.planned_quantity,t.actual_quantity,t.planned_productivity,t.workforce_trade FROM os_tasks t JOIN projects p ON p.id=t.project_id WHERE p.company_id=$1 AND t.status<>'na'`,[ctx.company_id])]);const capacity=capacityRows(activities.rows,people.rows),portfolio=portfolioCapacity(portfolioTasks.rows,people.rows,8),deficit=capacity.reduce((sum,row)=>sum+Math.max(0,-Number(row.balance||0)),0);send(res,200,{workers:people.rows,teams:teamRows.rows,allocations:allocations.rows,capacity,portfolio,activities:activities.rows,summary:{workers:people.rowCount,teams:teamRows.rowCount,plannedActivities:capacity.length,deficit}});return true}
  if(!staff(person)){send(res,403,{error:'Somente a equipe pode alterar capacidade e alocações.'});return true}
  if(workers&&req.method==='POST'){const body=await readJson(req),name=String(body?.name||'').trim().slice(0,160),trade=String(body?.trade||'').trim().slice(0,100);if(!name||!trade){send(res,400,{error:'Informe nome e função.'});return true}const q=await pool.query(`INSERT INTO workers(company_id,name,trade,contractor,availability_status) VALUES($1,$2,$3,$4,$5) RETURNING *`,[ctx.company_id,name,trade,String(body.contractor||'').trim().slice(0,160)||null,['available','allocated','unavailable'].includes(body.availabilityStatus)?body.availabilityStatus:'available']);send(res,201,{worker:q.rows[0]});return true}
  if(teams&&req.method==='POST'){const body=await readJson(req),name=String(body?.name||'').trim().slice(0,160);if(!name){send(res,400,{error:'Informe o nome da equipe.'});return true}const q=await pool.query(`INSERT INTO teams(company_id,name,trade) VALUES($1,$2,$3) RETURNING *`,[ctx.company_id,name,String(body.trade||'').trim().slice(0,100)||null]);send(res,201,{team:q.rows[0]});return true}
  if(activity&&req.method==='PATCH'){const body=await readJson(req),trade=String(body?.workforceTrade||'').trim().slice(0,100)||null,rate=body?.plannedProductivity===''?null:Number(body?.plannedProductivity);if(rate!==null&&(!(rate>0)||!Number.isFinite(rate))){send(res,400,{error:'A produtividade deve ser maior que zero.'});return true}const q=await pool.query(`UPDATE os_tasks SET workforce_trade=$1,planned_productivity=$2,updated_at=now() WHERE id=$3 AND project_id=$4 RETURNING *`,[trade,rate,Number(activity[2]),projectId]);if(!q.rowCount){send(res,404,{error:'Atividade não encontrada.'});return true}await event(projectId,person.id,`Capacidade planejada: ${q.rows[0].title}`,`${trade||'Função não definida'} · ${rate||'sem produtividade'} ${q.rows[0].unit||'un.'}/pessoa/dia`);send(res,200,{activity:q.rows[0]});return true}
  if(allocation&&req.method==='POST'){const body=await readJson(req),workerId=Number(body?.workerId)||null,teamId=Number(body?.teamId)||null,activityId=Number(body?.activityId)||null,start=iso(body?.startDate),end=iso(body?.endDate);if((!workerId&&!teamId)||!start||!end||end<start){send(res,400,{error:'Informe recurso e período válido.'});return true}if(workerId&&!(await pool.query('SELECT 1 FROM workers WHERE id=$1 AND company_id=$2 AND active=true',[workerId,ctx.company_id])).rowCount){send(res,400,{error:'Trabalhador não pertence à empresa.'});return true}if(teamId&&!(await pool.query('SELECT 1 FROM teams WHERE id=$1 AND company_id=$2 AND active=true',[teamId,ctx.company_id])).rowCount){send(res,400,{error:'Equipe não pertence à empresa.'});return true}if(activityId&&!(await pool.query('SELECT 1 FROM os_tasks WHERE id=$1 AND project_id=$2',[activityId,projectId])).rowCount){send(res,400,{error:'Atividade não pertence à obra.'});return true}const percent=Math.max(1,Math.min(100,Number(body.allocationPercent)||100));const q=await pool.query(`INSERT INTO allocations(project_id,activity_id,team_id,worker_id,start_date,end_date,allocation_percent) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[projectId,activityId,teamId,workerId,start,end,percent]);await event(projectId,person.id,'Alocação de mão de obra registrada',`${start} a ${end} · ${percent}%`);send(res,201,{allocation:q.rows[0]});return true}
  send(res,405,{error:'Método não permitido'});return true
 }
}
