import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowRight, Bot, Building2, Check, CheckCircle2, ChevronDown,
  ChevronRight, CircleDollarSign, ClipboardCheck, Construction, FileCheck2, FileText,
  Fingerprint, HardHat, Home, Landmark, Layers3, ListChecks, LogOut, MapPinned, Menu,
  Plus, RefreshCw, Ruler, Search, Send, Settings2, ShieldCheck, Sparkles, TimerReset,
  Users, WalletCards, Wrench, X
} from 'lucide-react'

type User = { id:number; name:string; email:string; role:'admin'|'team'|'client' }
type Project = { id:number; name:string; city?:string; address?:string; client_name?:string; status:string; budget:number|string; spent:number|string; updated_at?:string }
type Task = { id:number; code:string; stage_key:string; discipline:string; title:string; detail?:string; role?:string; required:boolean; priority:string; status:'pending'|'done'|'na'; client_action:boolean; source_label?:string; source_url?:string; legal_note?:string; task_order:number; is_custom:boolean }
type Stage = { num:string; key:string; title:string; summary:string; total:number; applicable:number; done:number; progress:number }
type Passport = { id:number; system_type:string; zone?:string; title:string; description?:string; photo_url?:string; warranty_until?:string; supplier?:string }
type Bundle = { project:Project; profile:any; workflowVersion?:string; tasks:Task[]; events:any[]; passport:Passport[]; stages:Stage[]; summary:{total:number;done:number;na:number;applicable:number;progress:number;nextTask?:Task|null} }
type View = 'home'|'roadmap'|'architecture'|'city'|'safety'|'execution'|'finance'|'passport'|'ai'|'settings'

const DISCIPLINE_META:Record<string,{label:string;color:string}> = {
  arquitetura:{label:'Arquitetura',color:'#B8633F'}, engenharia:{label:'Engenharia',color:'#355F7A'}, prefeitura:{label:'Prefeitura',color:'#7A5E39'}, federal:{label:'Federal',color:'#566670'}, sst:{label:'Segurança',color:'#B54B46'}, financeiro:{label:'Financeiro',color:'#5C7459'}, suprimentos:{label:'Suprimentos',color:'#88733E'}, gestao:{label:'Gestão',color:'#4D675C'}, qualidade:{label:'Qualidade',color:'#496E77'}, cliente:{label:'Cliente',color:'#7B5D83'}, passaporte:{label:'Passaporte',color:'#365F50'},
}

async function api<T=any>(url:string, options:RequestInit={}):Promise<T>{
  const r=await fetch(url,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}})
  const d=await r.json().catch(()=>({}))
  if(!r.ok) throw new Error(d.error||'Erro na operação')
  return d
}
const money=(v:any)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(v)||0)
const human=(v='')=>String(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const date=(v?:string)=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—'

export default function AppOS(){
  const[user,setUser]=useState<User|null>(null)
  const[loading,setLoading]=useState(true)
  useEffect(()=>{api('/api/me').then(r=>setUser(r.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[])
  if(loading)return <Splash/>
  if(!user)return <Login onLogin={setUser}/>
  return <Portal user={user} onLogout={()=>setUser(null)}/>
}

function Brand({compact=false}:{compact?:boolean}){return <div className={`os-brand ${compact?'compact':''}`}><span>O</span><div><b>OBRA360</b><small>OS</small></div></div>}
function Splash(){return <div className="os-splash"><Brand/><div className="splash-rule"><i/></div></div>}

function Login({onLogin}:{onLogin:(u:User)=>void}){
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(r.user)}catch(err:any){setError(err.message)}finally{setBusy(false)}}
  return <div className="os-login">
    <section className="os-login-left">
      <div className="blueprint-layer"/><Brand/>
      <div className="os-login-copy"><span className="eyebrow light">SISTEMA OPERACIONAL DA OBRA</span><h1>A obra já nasce com um caminho.</h1><p>Arquitetura, Prefeitura, engenharia, segurança do trabalho, execução, regularização e entrega organizadas em um roteiro automático. Você não começa de uma tela em branco.</p><div className="login-proof"><span><ListChecks size={17}/> etapas pré-definidas</span><span><MapPinned size={17}/> fluxo municipal</span><span><HardHat size={17}/> SST por fase</span></div></div>
      <div className="os-login-line"><span>TERRENO</span><i/><span>PROJETO</span><i/><span>OBRA</span><i/><span>ENTREGA</span></div>
    </section>
    <section className="os-login-right"><form onSubmit={submit}><span className="eyebrow">PORTAL OBRA360</span><h2>Entre na sua obra</h2><p>O portal mostra o que já foi concluído, o que vem agora e o que precisa ser resolvido para a obra continuar.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Entrar'} <ArrowRight size={17}/></button></form></section>
  </div>
}

function Portal({user,onLogout}:{user:User;onLogout:()=>void}){
  const staff=['admin','team'].includes(user.role)
  const[projects,setProjects]=useState<Project[]>([]);const[projectId,setProjectId]=useState<number|null>(null);const[b,setB]=useState<Bundle|null>(null);const[view,setView]=useState<View>('home');const[menu,setMenu]=useState(false);const[busy,setBusy]=useState(true)
  async function loadProjects(){const r=await api('/api/projects');setProjects(r.projects);if(!projectId&&r.projects[0])setProjectId(r.projects[0].id);setBusy(false)}
  async function load(){if(projectId)setB(await api(`/api/os/projects/${projectId}`))}
  useEffect(()=>{loadProjects().catch(()=>setBusy(false))},[])
  useEffect(()=>{if(projectId)load().catch(console.error)},[projectId])
  async function logout(){await api('/api/auth/logout',{method:'POST'}).catch(()=>{});onLogout()}
  if(busy)return <Splash/>
  if(!projects.length)return <EmptyProjects user={user} staff={staff} reload={loadProjects} logout={logout}/>
  const nav:[View,string,any][]=[['home','Agora na obra',Home],['roadmap','Roteiro completo',ListChecks],['architecture','Arquitetura & projetos',Ruler],['city','Prefeitura & regularização',Landmark],['safety','Segurança do trabalho',HardHat],['execution','Execução & qualidade',Construction],['finance','Planejamento & custos',WalletCards],['passport','Passaporte do imóvel',Fingerprint],['ai','Obra IA',Bot],...(staff?[['settings','Configurar obra',Settings2] as [View,string,any]]:[])]
  return <div className="os-shell">
    <aside className={`os-sidebar ${menu?'open':''}`}><div className="os-side-head"><Brand compact/><button className="mobile-close" onClick={()=>setMenu(false)}><X size={19}/></button></div><div className="active-project"><small>OBRA ATIVA</small><b>{b?.project.name||'Carregando…'}</b><span>{b?.project.city||'Município não informado'}</span></div><nav>{nav.map(([k,label,I])=><button key={k} onClick={()=>{setView(k);setMenu(false)}} className={view===k?'active':''}><I size={18}/><span>{label}</span>{k==='roadmap'&&b?<em>{b.summary.progress}%</em>:null}</button>)}</nav><div className="os-side-foot"><div className="user"><span>{user.name[0]?.toUpperCase()}</span><p><b>{user.name}</b><small>{user.role==='client'?'Cliente':'Equipe técnica'}</small></p></div><button onClick={logout}><LogOut size={17}/></button></div></aside>
    <main className="os-main"><header className="os-top"><button className="menu-btn" onClick={()=>setMenu(true)}><Menu size={20}/></button><div className="project-picker"><Building2 size={16}/><select value={projectId||''} onChange={e=>{setProjectId(Number(e.target.value));setB(null)}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ChevronDown size={14}/></div><div className="top-actions"><span>{b?.workflowVersion?`roteiro ${b.workflowVersion}`:'roteiro ainda não configurado'}</span><button onClick={()=>load()}><RefreshCw size={15}/> Atualizar</button></div></header>{!b?<div className="os-loading">Carregando obra…</div>:!b.profile?<Onboarding project={b.project} staff={staff} reload={load}/>:<Router view={view} b={b} user={user} staff={staff} reload={load}/>}</main>
  </div>
}

function EmptyProjects({user,staff,reload,logout}:{user:User;staff:boolean;reload:()=>void;logout:()=>void}){
  return <div className="empty-projects"><header><Brand/><button onClick={logout}><LogOut size={16}/> Sair</button></header><main><div className="empty-symbol"><Building2 size={34}/></div><span className="eyebrow">OBRA360 OS</span><h1>{staff?'Cadastre a primeira obra':'Nenhuma obra foi vinculada ao seu acesso'}</h1><p>{staff?'Depois do cadastro, o sistema fará algumas perguntas e montará automaticamente o roteiro completo da obra.':'Peça à equipe Obra360 para vincular seu acesso a um empreendimento.'}</p>{staff&&<CreateProject reload={reload}/>}</main></div>
}
function CreateProject({reload}:{reload:()=>void}){const[open,setOpen]=useState(false);const[msg,setMsg]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());try{await api('/api/projects',{method:'POST',body:JSON.stringify(body)});setOpen(false);reload()}catch(err:any){setMsg(err.message)}}if(!open)return <button className="primary compact" onClick={()=>setOpen(true)}><Plus size={17}/> Criar obra</button>;return <form className="create-project" onSubmit={submit}><div className="field-grid"><label>Nome da obra<input name="name" required placeholder="Ex.: Casa Silva"/></label><label>Município<input name="city" placeholder="Ex.: Viçosa, MG"/></label><label>Cliente<input name="clientName"/></label><label>Orçamento inicial<input name="budget" type="number" min="0"/></label></div>{msg&&<div className="form-error">{msg}</div>}<div className="form-actions"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary compact">Criar</button></div></form>}

function Onboarding({project,staff,reload}:{project:Project;staff:boolean;reload:()=>void}){
  const[step,setStep]=useState(0);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const[p,setP]=useState<any>({city:project.city||'',state:'MG',kind:'casa_nova',area:'',floors:1,lotOwned:true,slope:'plano',earthwork:false,basement:false,pool:false,elevator:false,solar:false,gas:false,treeRemoval:false,demolition:false,hasEmployees:false,multipleContractors:true,workAtHeight:false})
  if(!staff)return <div className="onboarding-readonly"><div><Sparkles size={28}/><h2>A equipe ainda está configurando o roteiro desta obra.</h2><p>Assim que o perfil técnico for concluído, o sistema mostrará automaticamente todas as etapas aplicáveis.</p></div></div>
  const steps=[
    <div className="on-step"><span className="eyebrow">1 DE 4 · PERFIL</span><h2>Que obra é essa?</h2><p>Estas respostas servem apenas para decidir quais etapas entram no roteiro.</p><div className="option-grid">{[['casa_nova','Casa nova','Residência unifamiliar'],['predio_residencial','Prédio residencial','Edificação multifamiliar'],['comercial_novo','Comercial novo','Loja, escritório ou outro uso'],['reforma','Reforma','Intervenção em imóvel existente'],['ampliacao','Ampliação','Acréscimo de área ou pavimento']].map(([v,t,s])=><button key={v} className={p.kind===v?'selected':''} onClick={()=>setP({...p,kind:v})}><b>{t}</b><small>{s}</small></button>)}</div><div className="field-grid"><label>Município<input value={p.city} onChange={e=>setP({...p,city:e.target.value})} placeholder="Viçosa, MG"/></label><label>Área aproximada (m²)<input type="number" value={p.area} onChange={e=>setP({...p,area:e.target.value})}/></label><label>Pavimentos<input type="number" min="1" value={p.floors} onChange={e=>setP({...p,floors:Number(e.target.value)})}/></label></div></div>,
    <div className="on-step"><span className="eyebrow">2 DE 4 · TERRENO</span><h2>Condições que mudam projeto e licenciamento</h2><Toggle label="Terreno com movimentação relevante de terra" checked={p.earthwork} onChange={(v)=>setP({...p,earthwork:v})}/><Toggle label="Inclinação acentuada" checked={p.slope==='acentuado'} onChange={(v)=>setP({...p,slope:v?'acentuado':'plano'})}/><Toggle label="Terá subsolo" checked={p.basement} onChange={(v)=>setP({...p,basement:v})}/><Toggle label="Haverá demolição" checked={p.demolition} onChange={(v)=>setP({...p,demolition:v})}/><Toggle label="Pode envolver corte ou remoção de árvore" checked={p.treeRemoval} onChange={(v)=>setP({...p,treeRemoval:v})}/></div>,
    <div className="on-step"><span className="eyebrow">3 DE 4 · SISTEMAS</span><h2>O que a obra terá?</h2><div className="toggle-grid"><Toggle label="Piscina" checked={p.pool} onChange={(v)=>setP({...p,pool:v})}/><Toggle label="Elevador" checked={p.elevator} onChange={(v)=>setP({...p,elevator:v})}/><Toggle label="Energia solar" checked={p.solar} onChange={(v)=>setP({...p,solar:v})}/><Toggle label="Instalação de gás" checked={p.gas} onChange={(v)=>setP({...p,gas:v})}/></div></div>,
    <div className="on-step"><span className="eyebrow">4 DE 4 · CANTEIRO</span><h2>Como será a execução?</h2><p>Isso ajuda o sistema a montar automaticamente a parte de segurança do trabalho.</p><Toggle label="Haverá empregados próprios na obra" checked={p.hasEmployees} onChange={(v)=>setP({...p,hasEmployees:v})}/><Toggle label="Haverá diferentes empreiteiros / empresas" checked={p.multipleContractors} onChange={(v)=>setP({...p,multipleContractors:v})}/><Toggle label="Haverá atividade com risco de queda / trabalho em altura" checked={p.workAtHeight} onChange={(v)=>setP({...p,workAtHeight:v})}/></div>
  ]
  async function finish(){setBusy(true);setError('');try{await api(`/api/os/projects/${project.id}/profile`,{method:'PUT',body:JSON.stringify(p)});await reload()}catch(err:any){setError(err.message)}finally{setBusy(false)}}
  return <div className="onboarding"><div className="onboarding-intro"><Brand/><span>CONFIGURAÇÃO AUTOMÁTICA</span><h1>Responda o essencial. O sistema monta o resto.</h1><p>O Obra360 cria o roteiro de arquitetura, prefeitura, engenharia, segurança, execução e entrega com base no perfil da obra.</p><div className="on-progress">{[0,1,2,3].map(i=><i key={i} className={i<=step?'active':''}/>)}</div></div><div className="onboarding-card">{steps[step]}{error&&<div className="form-error">{error}</div>}<div className="on-actions">{step>0?<button className="secondary" onClick={()=>setStep(step-1)}>Voltar</button>:<span/>}{step<3?<button className="primary compact" onClick={()=>setStep(step+1)}>Continuar <ArrowRight size={16}/></button>:<button className="primary compact" onClick={finish} disabled={busy}>{busy?'Montando…':'Gerar roteiro da obra'} <Sparkles size={16}/></button>}</div></div></div>
}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" className={`toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span><i>{checked?<Check size={14}/>:null}</i><b>{label}</b></span><em>{checked?'Sim':'Não'}</em></button>}

function Router({view,b,user,staff,reload}:{view:View;b:Bundle;user:User;staff:boolean;reload:()=>void}){
  if(view==='home')return <HomeView b={b} staff={staff} reload={reload}/>
  if(view==='roadmap')return <Roadmap b={b} user={user} staff={staff} reload={reload}/>
  if(view==='architecture')return <DisciplinePage b={b} user={user} staff={staff} reload={reload} title="Arquitetura & projetos" subtitle="Da leitura do terreno ao projeto executivo compatibilizado, com aprovações do cliente nos pontos certos." filters={['arquitetura']} icon={Ruler}/>
  if(view==='city')return <CityPage b={b} user={user} staff={staff} reload={reload}/>
  if(view==='safety')return <SafetyPage b={b} user={user} staff={staff} reload={reload}/>
  if(view==='execution')return <DisciplinePage b={b} user={user} staff={staff} reload={reload} title="Execução & qualidade" subtitle="Checklists por etapa para reduzir improviso, registrar o que ficará oculto e liberar o próximo serviço com evidência." filters={['engenharia','qualidade','passaporte']} icon={Construction}/>
  if(view==='finance')return <FinancePage b={b} user={user} staff={staff} reload={reload}/>
  if(view==='passport')return <PassportPage b={b} staff={staff} reload={reload}/>
  if(view==='ai')return <AIPage b={b}/>
  return <SettingsPage b={b} reload={reload}/>
}

function PageHead({tag,title,text,right}:{tag:string;title:string;text:string;right?:any}){return <div className="page-head"><div><span className="eyebrow">{tag}</span><h1>{title}</h1><p>{text}</p></div>{right}</div>}

function HomeView({b,staff,reload}:{b:Bundle;staff:boolean;reload:()=>void}){
  const next=b.summary.nextTask
  const arch=b.tasks.filter(t=>t.discipline==='arquitetura'&&t.status!=='na');const safety=b.tasks.filter(t=>t.discipline==='sst'&&t.status!=='na');const city=b.tasks.filter(t=>['prefeitura','federal'].includes(t.discipline)&&t.status!=='na')
  return <div className="page"><PageHead tag="AGORA NA OBRA" title="O sistema diz o próximo passo." text="Em vez de procurar o que fazer em várias telas, o Obra360 prioriza a ação seguinte e mostra o impacto dela no restante da obra." right={<div className="overall-progress"><span>{b.summary.progress}%</span><small>roteiro concluído</small></div>}/>
    <section className="next-action"><div className="next-number">01</div><div className="next-copy"><span>PRÓXIMA AÇÃO PRIORITÁRIA</span><h2>{next?.title||'Nenhuma pendência registrada'}</h2><p>{next?.detail||'O roteiro atual não possui itens pendentes.'}</p>{next&&<div className="next-tags"><Badge discipline={next.discipline}/><span>{roleLabel(next.role)}</span><span className={`priority ${next.priority}`}>{priorityLabel(next.priority)}</span></div>}</div>{next&&<TaskActions task={next} staff={staff} reload={reload} projectId={b.project.id}/>}</section>
    <section className="signal-grid"><Signal icon={Ruler} label="Arquitetura" value={`${arch.filter(t=>t.status==='done').length}/${arch.length}`} text="itens concluídos"/><Signal icon={Landmark} label="Prefeitura & regularização" value={`${city.filter(t=>t.status==='done').length}/${city.length}`} text="itens concluídos"/><Signal icon={HardHat} label="Segurança do trabalho" value={`${safety.filter(t=>t.status==='done').length}/${safety.length}`} text="itens concluídos"/><Signal icon={CircleDollarSign} label="Orçamento cadastrado" value={money(b.project.budget)} text={b.project.budget?'linha de base financeira':'a definir'}/></section>
    <section className="home-grid"><article className="panel"><div className="panel-head"><div><span>CAMINHO DA OBRA</span><h3>15 etapas, uma sequência</h3></div><Layers3 size={19}/></div><div className="stage-mini-list">{b.stages.slice(0,8).map(s=><div key={s.key}><span>{s.num}</span><div><b>{s.title}</b><i><em style={{width:`${s.progress}%`}}/></i></div><strong>{s.progress}%</strong></div>)}</div></article><article className="panel"><div className="panel-head"><div><span>O QUE NÃO DEPENDE DE DIGITAÇÃO</span><h3>O roteiro já veio pronto</h3></div><Sparkles size={19}/></div><div className="automation-copy"><p>O sistema gerou <b>{b.summary.total} ações</b> com base no perfil informado. Você trabalha principalmente marcando <strong>Concluído</strong>, <strong>Não se aplica</strong> ou abrindo o detalhe quando precisa de fonte e orientação.</p><div className="automation-metrics"><span><b>{b.summary.done}</b><small>concluídos</small></span><span><b>{b.summary.na}</b><small>não aplicáveis</small></span><span><b>{b.summary.applicable-b.summary.done}</b><small>restantes</small></span></div></div></article></section>
  </div>
}
function Signal({icon:I,label,value,text}:{icon:any;label:string;value:string;text:string}){return <article className="signal"><div><I size={18}/><span>{label}</span></div><strong>{value}</strong><small>{text}</small></article>}

function Roadmap({b,user,staff,reload}:{b:Bundle;user:User;staff:boolean;reload:()=>void}){
  const[open,setOpen]=useState<string>(b.stages.find(s=>s.progress<100)?.key||b.stages[0]?.key||'');const[query,setQuery]=useState('')
  return <div className="page"><PageHead tag="ROTEIRO AUTOMÁTICO" title="A obra inteira, etapa por etapa." text="As etapas são pré-definidas. Você apenas valida o que foi feito, marca o que não se aplica e acrescenta exceções quando necessário." right={<div className="route-count"><b>{b.summary.total}</b><small>ações geradas</small></div>}/><div className="toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar etapa, documento, serviço ou responsável"/></div></div><div className="roadmap">{b.stages.map(stage=>{const rows=b.tasks.filter(t=>t.stage_key===stage.key&&(`${t.title} ${t.detail} ${t.discipline}`).toLowerCase().includes(query.toLowerCase()));if(query&&rows.length===0)return null;return <article className="road-stage" key={stage.key}><button className="road-stage-head" onClick={()=>setOpen(open===stage.key?'':stage.key)}><span className="stage-num">{stage.num}</span><div className="stage-name"><small>{stage.done}/{stage.applicable} concluídos</small><h3>{stage.title}</h3><p>{stage.summary}</p></div><div className="stage-progress"><strong>{stage.progress}%</strong><i><em style={{width:`${stage.progress}%`}}/></i></div><ChevronRight size={18} className={open===stage.key?'rotated':''}/></button>{open===stage.key&&<div className="road-tasks">{rows.map(t=><TaskRow key={t.id} task={t} user={user} staff={staff} projectId={b.project.id} reload={reload}/>) }{staff&&<AddTask projectId={b.project.id} stageKey={stage.key} reload={reload}/>}</div>}</article>})}</div></div>
}

function DisciplinePage({b,user,staff,reload,title,subtitle,filters,icon:I}:{b:Bundle;user:User;staff:boolean;reload:()=>void;title:string;subtitle:string;filters:string[];icon:any}){
  const rows=b.tasks.filter(t=>filters.includes(t.discipline));const byStage=b.stages.map(s=>({...s,tasks:rows.filter(t=>t.stage_key===s.key)})).filter(s=>s.tasks.length)
  return <div className="page"><PageHead tag="FLUXO ESPECIALIZADO" title={title} text={subtitle} right={<div className="head-icon"><I size={24}/></div>}/><div className="discipline-summary"><span><b>{rows.filter(t=>t.status==='done').length}</b><small>concluídos</small></span><span><b>{rows.filter(t=>t.status==='pending').length}</b><small>pendentes</small></span><span><b>{rows.filter(t=>t.status==='na').length}</b><small>não aplicáveis</small></span></div><div className="discipline-flow">{byStage.map(stage=><section key={stage.key}><div className="discipline-stage-title"><span>{stage.num}</span><div><h3>{stage.title}</h3><p>{stage.summary}</p></div></div><div className="task-stack">{stage.tasks.map(t=><TaskRow key={t.id} task={t} user={user} staff={staff} projectId={b.project.id} reload={reload}/>)}</div></section>)}</div></div>
}

function CityPage({b,user,staff,reload}:{b:Bundle;user:User;staff:boolean;reload:()=>void}){
  const rows=b.tasks.filter(t=>['prefeitura','federal'].includes(t.discipline));const vicosa=(b.profile?.city||b.project.city||'').toLowerCase().includes('viçosa')||(b.profile?.city||b.project.city||'').toLowerCase().includes('vicosa')
  const groups=[['Antes de protocolar',['terreno','arquitetura']],['Aprovação e Alvará',['legal']],['Antes de iniciar a obra',['mobilizacao']],['Conclusão e Habite-se',['conclusao']],['Receita e averbação',['conclusao','entrega']]]
  return <div className="page"><PageHead tag="PREFEITURA & REGULARIZAÇÃO" title={vicosa?'Passo a passo para Viçosa':'Roteiro municipal da obra'} text={vicosa?'O portal organiza o caminho desde documentos do imóvel e projeto legal até Habite-se, ISS da obra, Sero e averbação. Itens municipais são acompanhados com a fonte disponível e precisam ser validados conforme o protocolo vigente.':'O roteiro usa uma base geral e deve ser ajustado às exigências do município selecionado.'} right={<div className="jurisdiction"><MapPinned size={18}/><div><small>PACOTE MUNICIPAL</small><b>{vicosa?'Viçosa · MG':'Genérico'}</b></div></div>}/><div className="city-stepper">{groups.map(([label,stageKeys],index)=>{let groupRows=rows.filter(t=>(stageKeys as string[]).includes(t.stage_key));if(index===0)groupRows=b.tasks.filter(t=>['property_title','iptu_registry','urban_parameters','legal_arch_project','rrt_art_project'].includes(t.code));if(index===4)groupRows=rows.filter(t=>['sero_regularization','registry_update','vicosa_cadastral_update'].includes(t.code));return <section key={label as string}><div className="city-index">{String(index+1).padStart(2,'0')}</div><div className="city-block"><span className="eyebrow">{label as string}</span><div className="task-stack">{groupRows.map(t=><TaskRow key={t.id} task={t} user={user} staff={staff} projectId={b.project.id} reload={reload} sourceFirst/>)}</div></div></section>})}</div><div className="legal-notice"><Landmark size={21}/><div><b>O sistema conduz; o órgão público decide.</b><p>O Obra360 não presume que uma exigência municipal antiga continua idêntica. Por isso, cada pacote municipal deve ser versionado e atualizado com fonte oficial. O profissional responsável confirma o enquadramento antes do protocolo.</p></div></div></div>
}

function SafetyPage({b,user,staff,reload}:{b:Bundle;user:User;staff:boolean;reload:()=>void}){
  const rows=b.tasks.filter(t=>t.discipline==='sst');const critical=rows.filter(t=>t.priority==='critica'&&t.status==='pending');
  return <div className="page"><PageHead tag="ENGENHARIA DE SEGURANÇA" title="SST acompanha a fase da obra." text="Em vez de um PGR esquecido em PDF, o roteiro muda com a execução: mobilização, escavação, estrutura, altura, elétrica e demais riscos aparecem no momento em que importam." right={<div className={`safety-pulse ${critical.length?'attention':''}`}><ShieldCheck size={22}/><div><b>{critical.length}</b><small>críticos pendentes</small></div></div>}/><div className="safety-callout"><div><HardHat size={25}/><h3>Motor de aplicabilidade</h3></div><p>As respostas do perfil da obra ativam itens como PGR, SCPO, proteção contra quedas, integração de contratados, PCMSO/ASO quando informado vínculo empregatício e controles específicos por fase. A validação final continua sendo técnica.</p></div><div className="risk-lanes">{b.stages.map(s=>{const list=rows.filter(t=>t.stage_key===s.key);if(!list.length)return null;return <section key={s.key}><div className="risk-stage"><span>{s.num}</span><div><h3>{s.title}</h3><p>{list.filter(t=>t.status==='pending').length} pendência(s) de SST</p></div></div><div className="task-stack">{list.map(t=><TaskRow key={t.id} task={t} user={user} staff={staff} projectId={b.project.id} reload={reload}/>)}</div></section>})}</div></div>
}

function FinancePage({b,user,staff,reload}:{b:Bundle;user:User;staff:boolean;reload:()=>void}){
  const rows=b.tasks.filter(t=>['financeiro','suprimentos','gestao'].includes(t.discipline));
  return <div className="page"><PageHead tag="PLANEJAMENTO & CUSTOS" title="O financeiro começa antes da primeira compra." text="Orçamento, fluxo de caixa, cronograma, contratos e mapa de compras entram no roteiro antes da execução para reduzir decisão atrasada e compra emergencial." right={<div className="budget-box"><small>ORÇAMENTO CADASTRADO</small><b>{money(b.project.budget)}</b></div>}/><div className="finance-principles"><article><TimerReset size={19}/><b>Quando comprar?</b><p>O mapa de compras se conecta às etapas e antecedências críticas.</p></article><article><WalletCards size={19}/><b>Quanto deveria gastar?</b><p>A linha de base financeira deve nascer do projeto compatibilizado.</p></article><article><ClipboardCheck size={19}/><b>O que foi contratado?</b><p>Escopos claros reduzem disputa de responsabilidade e retrabalho.</p></article></div><div className="task-stack roomy">{rows.map(t=><TaskRow key={t.id} task={t} user={user} staff={staff} projectId={b.project.id} reload={reload}/>)}</div></div>
}

function PassportPage({b,staff,reload}:{b:Bundle;staff:boolean;reload:()=>void}){
  const[q,setQ]=useState('');const[open,setOpen]=useState(false);const rows=b.passport.filter(i=>(`${i.title} ${i.zone||''} ${i.system_type} ${i.description||''}`).toLowerCase().includes(q.toLowerCase()))
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());await api(`/api/os/projects/${b.project.id}/passport`,{method:'POST',body:JSON.stringify(body)});setOpen(false);reload()}
  return <div className="page"><PageHead tag="PASSAPORTE DO IMÓVEL" title="Documente o que vai ficar escondido." text="Tubulações, eletrodutos, impermeabilização, equipamentos, fornecedores e garantias continuam consultáveis depois que a obra termina." right={staff?<button className="primary compact" onClick={()=>setOpen(!open)}><Plus size={16}/> Registrar item</button>:null}/>{open&&<form className="passport-form" onSubmit={submit}><div className="field-grid"><label>Sistema<select name="systemType"><option value="hidraulica">Hidráulica</option><option value="eletrica">Elétrica</option><option value="impermeabilizacao">Impermeabilização</option><option value="estrutura">Estrutura</option><option value="equipamento">Equipamento</option><option value="acabamento">Acabamento</option></select></label><label>Ambiente / zona<input name="zone" placeholder="Ex.: banheiro suíte"/></label><label className="span2">Título<input name="title" required placeholder="Ex.: Tubulação parede norte"/></label><label className="span2">Descrição<textarea name="description" rows={3}/></label><label>Fornecedor<input name="supplier"/></label><label>Garantia até<input name="warrantyUntil" type="date"/></label></div><div className="form-actions right"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary compact">Salvar</button></div></form>}<div className="toolbar"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar parede, banheiro, tubulação, equipamento…"/></div></div><div className="passport-grid">{rows.map(i=><article key={i.id}><span>{human(i.system_type)}</span><h3>{i.title}</h3><p>{i.description||'Sem descrição adicional.'}</p><div><small>{i.zone||'Sem ambiente definido'}</small>{i.warranty_until&&<small>Garantia: {date(i.warranty_until)}</small>}</div></article>)}{!rows.length&&<Empty icon={Fingerprint} title="O passaporte ainda está vazio" text="Durante a execução, registre principalmente o que ficará oculto e o que terá garantia ou manutenção futura."/>}</div></div>
}

function AIPage({b}:{b:Bundle}){
  const[messages,setMessages]=useState<{role:'user'|'assistant';text:string}[]>([{role:'assistant',text:`Posso consultar o roteiro de ${b.project.name}. Pergunte o que falta para ir à Prefeitura, quais etapas de arquitetura ainda estão pendentes, o que precisa ser feito em segurança ou qual é a próxima ação da obra.`}]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages]);async function ask(q=text){if(!q.trim()||busy)return;setMessages(m=>[...m,{role:'user',text:q}]);setText('');setBusy(true);try{const r=await api(`/api/os/projects/${b.project.id}/ai`,{method:'POST',body:JSON.stringify({question:q})});setMessages(m=>[...m,{role:'assistant',text:r.answer}])}catch(err:any){setMessages(m=>[...m,{role:'assistant',text:err.message}])}finally{setBusy(false)}}return <div className="page ai-page"><PageHead tag="OBRA IA" title="Pergunte ao roteiro da obra." text="A IA consulta o perfil e os itens registrados. Ela não deve inventar exigência municipal nem substituir a validação dos profissionais responsáveis." right={<span className="ai-context"><Sparkles size={15}/> contexto real da obra</span>}/><div className="ai-shell"><aside><span className="eyebrow">SUGESTÕES</span>{['O que falta antes de protocolar na Prefeitura?','Quais etapas de arquitetura faltam?','O que preciso resolver em SST agora?','Qual é a próxima ação prioritária?','O que falta para concluir a obra?'].map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</aside><section><div className="messages">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.role==='assistant'&&<span><Bot size={17}/></span>}<p>{m.text}</p></div>)}{busy&&<div className="message assistant"><span><Bot size={17}/></span><p>Consultando o roteiro…</p></div>}<div ref={end}/></div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Pergunte sobre a obra"/><button onClick={()=>ask()} disabled={!text.trim()||busy}><Send size={17}/></button></div></section></div></div>
}

function SettingsPage({b,reload}:{b:Bundle;reload:()=>void}){const[show,setShow]=useState(false);return <div className="page"><PageHead tag="CONFIGURAÇÃO" title="Perfil que alimenta o roteiro" text="Se a obra mudar de escopo, o motor pode recalcular quais tarefas são aplicáveis sem apagar o que já foi concluído."/><div className="settings-card"><div><Settings2 size={22}/><h3>Perfil atual</h3></div><dl><div><dt>Tipo</dt><dd>{human(b.profile?.kind||'')}</dd></div><div><dt>Município</dt><dd>{b.profile?.city||b.project.city||'—'}</dd></div><div><dt>Área</dt><dd>{b.profile?.area?`${b.profile.area} m²`:'—'}</dd></div><div><dt>Pavimentos</dt><dd>{b.profile?.floors||'—'}</dd></div><div><dt>Empregados próprios</dt><dd>{b.profile?.hasEmployees?'Sim':'Não'}</dd></div><div><dt>Múltiplos contratados</dt><dd>{b.profile?.multipleContractors?'Sim':'Não'}</dd></div></dl><button className="secondary" onClick={()=>setShow(!show)}>Reconfigurar roteiro</button>{show&&<ProfileEditor b={b} reload={reload}/>}</div></div>}
function ProfileEditor({b,reload}:{b:Bundle;reload:()=>void}){const[p,setP]=useState({...b.profile});async function save(){await api(`/api/os/projects/${b.project.id}/profile`,{method:'PUT',body:JSON.stringify(p)});await reload()}return <div className="profile-editor"><div className="toggle-grid"><Toggle label="Movimentação relevante de terra" checked={!!p.earthwork} onChange={v=>setP({...p,earthwork:v})}/><Toggle label="Subsolo" checked={!!p.basement} onChange={v=>setP({...p,basement:v})}/><Toggle label="Piscina" checked={!!p.pool} onChange={v=>setP({...p,pool:v})}/><Toggle label="Elevador" checked={!!p.elevator} onChange={v=>setP({...p,elevator:v})}/><Toggle label="Energia solar" checked={!!p.solar} onChange={v=>setP({...p,solar:v})}/><Toggle label="Gás" checked={!!p.gas} onChange={v=>setP({...p,gas:v})}/><Toggle label="Empregados próprios" checked={!!p.hasEmployees} onChange={v=>setP({...p,hasEmployees:v})}/><Toggle label="Vários contratados" checked={!!p.multipleContractors} onChange={v=>setP({...p,multipleContractors:v})}/></div><button className="primary compact" onClick={save}><RefreshCw size={16}/> Recalcular roteiro</button></div>}

function TaskRow({task,user,staff,projectId,reload,sourceFirst=false}:{task:Task;user:User;staff:boolean;projectId:number;reload:()=>void;sourceFirst?:boolean}){
  const[open,setOpen]=useState(false);const canEdit=staff||task.client_action
  return <article className={`task-row ${task.status} priority-${task.priority}`}><button className="task-check" disabled={!canEdit} onClick={async()=>{if(!canEdit)return;const next=task.status==='done'?'pending':'done';await api(`/api/os/projects/${projectId}/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:next})});reload()}}>{task.status==='done'?<Check size={16}/>:task.status==='na'?<X size={15}/>:null}</button><div className="task-main" onClick={()=>setOpen(!open)}><div className="task-topline"><Badge discipline={task.discipline}/>{task.required&&<span className="required">obrigatório no roteiro</span>}{task.client_action&&<span className="client-action">ação do cliente</span>}</div><h3>{task.title}</h3>{sourceFirst&&task.source_label&&<a onClick={e=>e.stopPropagation()} href={task.source_url} target="_blank" rel="noreferrer">{task.source_label} ↗</a>}{open&&<div className="task-detail"><p>{task.detail}</p><div className="task-meta"><span>Responsável: <b>{roleLabel(task.role)}</b></span><span>Prioridade: <b>{priorityLabel(task.priority)}</b></span>{task.source_label&& !sourceFirst?<a href={task.source_url} target="_blank" rel="noreferrer">Fonte: {task.source_label} ↗</a>:null}</div>{task.legal_note&&<div className="legal-note"><AlertTriangle size={15}/><span>{task.legal_note}</span></div>}</div>}</div><div className="task-actions">{canEdit&&task.status==='pending'&&<button className="na-btn" onClick={async()=>{await api(`/api/os/projects/${projectId}/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:'na'})});reload()}}>N/A</button>}<button className="detail-btn" onClick={()=>setOpen(!open)}><ChevronDown size={16} className={open?'up':''}/></button></div></article>
}
function TaskActions({task,staff,reload,projectId}:{task:Task;staff:boolean;reload:()=>void;projectId:number}){if(!staff&&!task.client_action)return <span className="waiting-team">aguardando equipe</span>;return <button className="complete-action" onClick={async()=>{await api(`/api/os/projects/${projectId}/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:'done'})});reload()}}><CheckCircle2 size={18}/> Marcar concluído</button>}
function Badge({discipline}:{discipline:string}){const m=DISCIPLINE_META[discipline]||{label:human(discipline),color:'#60736A'};return <span className="badge" style={{'--badge-color':m.color} as any}>{m.label}</span>}
function roleLabel(v?:string){return ({cliente:'Cliente',arquiteto:'Arquiteto(a)',engenheiro_civil:'Eng. Civil',engenheiro_producao:'Eng. Produção / Gestão',engenheiro_seguranca:'Eng. Segurança',engenheiro_eletricista:'Eng. Eletricista',medico_trabalho:'Médico do Trabalho',equipe:'Equipe técnica'} as Record<string,string>)[v||'']||human(v||'Equipe')}
function priorityLabel(v:string){return v==='critica'?'Crítica':v==='alta'?'Alta':'Normal'}

function AddTask({projectId,stageKey,reload}:{projectId:number;stageKey:string;reload:()=>void}){const[open,setOpen]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());await api(`/api/os/projects/${projectId}/tasks`,{method:'POST',body:JSON.stringify({...body,stageKey})});setOpen(false);reload()}if(!open)return <button className="add-task" onClick={()=>setOpen(true)}><Plus size={15}/> Adicionar item específico</button>;return <form className="inline-add" onSubmit={submit}><input name="title" required placeholder="Nome do item adicional"/><select name="discipline"><option value="gestao">Gestão</option><option value="arquitetura">Arquitetura</option><option value="engenharia">Engenharia</option><option value="sst">Segurança</option><option value="prefeitura">Prefeitura</option><option value="financeiro">Financeiro</option></select><input name="detail" placeholder="Observação opcional"/><button className="primary compact">Adicionar</button><button type="button" onClick={()=>setOpen(false)}>Cancelar</button></form>}

function Empty({icon:I,title,text}:{icon:any;title:string;text:string}){return <div className="empty"><I size={28}/><h3>{title}</h3><p>{text}</p></div>}
