import {useRef,useState} from 'react'
import {CheckCircle2,LoaderCircle,Mic,MicOff,Sparkles} from 'lucide-react'
async function api(url:string,options:RequestInit={}){const r=await fetch(url,{...options,credentials:'include',headers:{'Content-Type':'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro na operação');return d}
export default function FieldVoiceCapture({projectId,activities,close,notify,complete}:{projectId:number;activities:any[];close:()=>void;notify:(m:string)=>void;complete:()=>Promise<void>}){
 const[transcript,setTranscript]=useState(''),[listening,setListening]=useState(false),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>(null),rec=useRef<any>(null)
 function listen(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){notify('Este navegador não oferece reconhecimento de voz. Digite o relato.');return}const r=new SR();r.lang='pt-BR';r.continuous=true;r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=(event:any)=>{let value='';for(let i=event.resultIndex;i<event.results.length;i++)value+=event.results[i][0].transcript+' ';setTranscript(old=>(old+' '+value).trim())};r.onerror=()=>{setListening(false);notify('Não consegui ouvir. Confira a permissão do microfone.')};rec.current=r;r.start()}
 function stop(){try{rec.current?.stop()}catch{}setListening(false)}
 async function interpret(){if(!transcript.trim())return notify('Fale ou digite o relato.');stop();setBusy(true);try{const r=await api(`/api/vico/projects/${projectId}/field/voice-preview`,{method:'POST',body:JSON.stringify({transcript})});setPreview(r.preview)}catch(e:any){notify(e.message)}finally{setBusy(false)}}
 function production(key:string,value:any){setPreview({...preview,production:{...preview.production,[key]:value}})}
 async function confirm(){if(!preview)return;setBusy(true);try{const report=await api(`/api/vico/projects/${projectId}/daily-reports`,{method:'POST',body:JSON.stringify(preview.report)}),reportId=report.report?.id;if(preview.production?.activityId&&preview.production?.quantity!==null&&preview.production?.quantity!==''){await api(`/api/vico/projects/${projectId}/productivity`,{method:'POST',body:JSON.stringify({...preview.production,dailyReportId:reportId,recordDate:preview.report.reportDate})})}if(preview.occurrence?.title){await api(`/api/vico/projects/${projectId}/occurrences`,{method:'POST',body:JSON.stringify({...preview.occurrence,dailyReportId:reportId})})}await complete();notify('Relato confirmado e salvo como RDO em rascunho.');close()}catch(e:any){notify(e.message)}finally{setBusy(false)}}
 return <div className="field-modal field-voice-modal" role="dialog" aria-modal="true"><div className="field-voice-card"><header><div><span>IA SUGERE · HUMANO CONFIRMA</span><h2>Apontamento por voz</h2></div><button onClick={close}>×</button></header><button className={`field-voice-button ${listening?'listening':''}`} onClick={listening?stop:listen}>{listening?<MicOff/>:<Mic/>}<span>{listening?'Parar gravação':'Falar relato de campo'}</span></button><label>Relato<textarea value={transcript} onChange={e=>{setTranscript(e.target.value);setPreview(null)}} placeholder="Hoje vieram cinco pedreiros..."/></label><button className="v4-primary" disabled={busy||!transcript.trim()} onClick={interpret}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>} Interpretar sem lançar</button>{preview&&<section className="field-voice-review"><span>{preview.mode==='gemini'?'INTERPRETAÇÃO COM IA':'INTERPRETAÇÃO ESTRUTURADA'} · revisar todos os campos</span><label>Atividade<select value={preview.production.activityId||''} onChange={e=>production('activityId',e.target.value)}><option value="">Não identificada</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><div><label>Quantidade<input type="number" step="0.001" value={preview.production.quantity??''} onChange={e=>production('quantity',e.target.value)}/></label><label>Unidade<input value={preview.production.unit||''} onChange={e=>production('unit',e.target.value)}/></label><label>Trabalhadores<input type="number" min="0" value={preview.production.workerCount||0} onChange={e=>production('workerCount',e.target.value)}/></label><label>Horas trabalhadas<input type="number" min="0" step="0.25" value={preview.production.workedHours||0} onChange={e=>production('workedHours',e.target.value)}/></label><label>Horas paradas<input type="number" min="0" step="0.25" value={preview.production.downtimeHours||0} onChange={e=>production('downtimeHours',e.target.value)}/></label><label>Motivo<input value={preview.production.downtimeReason||''} onChange={e=>production('downtimeReason',e.target.value)}/></label></div><label>Resumo do RDO<textarea value={preview.report.notes||''} onChange={e=>setPreview({...preview,report:{...preview.report,notes:e.target.value}})}/></label><p>Equipe interpretada: {Object.entries(preview.workforce?.roles||{}).map(([role,count])=>`${count} ${role}`).join(', ')||'não identificada'}. Ausências: {preview.workforce?.absences?.join(', ')||'nenhuma identificada'}.</p><button className="v4-primary" disabled={busy} onClick={confirm}><CheckCircle2/> Confirmar e registrar</button></section>}</div></div>
}
