import { FormEvent, useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, ClipboardCheck, Gauge, LoaderCircle, Plus, TimerReset, Users } from 'lucide-react'

type Activity={id:number;title:string;wbs_code?:string;unit?:string;planned_quantity?:number|string;actual_quantity?:number|string;planned_productivity?:number|string;actual_productivity?:number|string}
type Report={id:number;report_date:string;weather?:string;notes?:string;status:'draft'|'confirmed';productivity_count:number;labor_hours:number|string;downtime_hours:number|string;created_by_name?:string}
type Record={id:number;record_date:string;activity_title:string;wbs_code?:string;quantity:number|string;unit:string;worked_hours:number|string;worker_count:number;downtime_hours:number|string;productivity_per_labor_hour?:number|string}
type Occurrence={id:number;occurrence_type:string;title:string;description?:string;activity_title?:string;impact_days?:number|string;created_at:string}
type FieldData={reports:Report[];records:Record[];occurrences:Occurrence[];activities:Activity[];summary:{reports:number;confirmed:number;records:number;laborHours:number;downtimeHours:number}}
async function request(url:string,options:RequestInit={}){const r=await fetch(url,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro na operação');return d}
const today=()=>new Date().toISOString().slice(0,10)
const dateValue=(value:string)=>String(value).slice(0,10)
const human=(value='')=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const number=(value:any,digits=2)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:digits}).format(Number(value)||0)

export default function FieldOperations({projectId,notify}:{projectId:number;notify:(message:string)=>void}){
  const[data,setData]=useState<FieldData|null>(null),[tab,setTab]=useState<'rdo'|'production'|'occurrences'>('rdo'),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[showRdo,setShowRdo]=useState(false),[showProduction,setShowProduction]=useState(false),[showOccurrence,setShowOccurrence]=useState(false)
  async function load(){setError('');try{setData(await request(`/api/vico/projects/${projectId}/field`))}catch(e:any){setError(e.message)}}
  useEffect(()=>{setData(null);load()},[projectId])
  async function save(url:string,body:any,message:string){setBusy(true);try{await request(url,{method:'POST',body:JSON.stringify(body)});await load();window.dispatchEvent(new CustomEvent('obra360:refresh'));notify(message);return true}catch(e:any){notify(e.message);return false}finally{setBusy(false)}}
  async function confirm(id:number){setBusy(true);try{await request(`/api/vico/projects/${projectId}/daily-reports/${id}/confirm`,{method:'PATCH'});await load();notify('RDO confirmado.')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
  if(error)return <div className="v4-page"><div className="v4-form-error">{error}</div></div>
  if(!data)return <div className="v4-loading">Carregando dados de campo…</div>
  return <div className="v4-page field-page"><header className="field-head"><div><span>CAMPO · RDO · PRODUTIVIDADE</span><h1>O que aconteceu na obra.</h1><p>Registros confirmados alimentam o histórico operacional. Nenhuma ocorrência altera o cronograma automaticamente.</p></div><div><button onClick={()=>setShowRdo(true)}><ClipboardCheck size={16}/> Novo RDO</button><button className="v4-primary" onClick={()=>setShowProduction(true)}><Plus size={16}/> Registrar produção</button></div></header>
    <section className="field-summary"><article><ClipboardCheck/><span><b>{data.summary.confirmed}</b><small>RDOs confirmados</small></span></article><article><Gauge/><span><b>{data.summary.records}</b><small>apontamentos</small></span></article><article><Users/><span><b>{number(data.summary.laborHours,1)}</b><small>horas-homem</small></span></article><article className={data.summary.downtimeHours?'warning':''}><TimerReset/><span><b>{number(data.summary.downtimeHours,1)}h</b><small>paralisação</small></span></article></section>
    <div className="field-tabs"><button className={tab==='rdo'?'active':''} onClick={()=>setTab('rdo')}>Diário de obra</button><button className={tab==='production'?'active':''} onClick={()=>setTab('production')}>Produtividade</button><button className={tab==='occurrences'?'active':''} onClick={()=>setTab('occurrences')}>Ocorrências <em>{data.occurrences.length}</em></button></div>
    {tab==='rdo'&&<section className="field-panel"><header><div><span>REGISTROS DIÁRIOS</span><h2>RDOs recentes</h2></div></header><div className="field-report-list">{data.reports.map(report=><article key={report.id}><div className={`field-report-date ${report.status}`}><b>{new Date(`${dateValue(report.report_date)}T12:00:00`).getDate()}</b><span>{new Date(`${dateValue(report.report_date)}T12:00:00`).toLocaleDateString('pt-BR',{month:'short'})}</span></div><div><span>{report.status==='confirmed'?'CONFIRMADO':'RASCUNHO'} · {report.weather||'Clima não informado'}</span><h3>{report.notes||'Sem observações gerais.'}</h3><small>{report.productivity_count} apontamento(s) · {number(report.labor_hours,1)} h-h · {number(report.downtime_hours,1)}h paradas</small></div>{report.status==='draft'&&<button disabled={busy} onClick={()=>confirm(report.id)}><CheckCircle2 size={16}/> Confirmar</button>}</article>)}{!data.reports.length&&<p className="field-empty">Nenhum RDO registrado.</p>}</div></section>}
    {tab==='production'&&<section className="field-panel"><header><div><span>MEDIÇÕES</span><h2>Produção registrada</h2></div></header><div className="field-production-list">{data.records.map(record=><article key={record.id}><div><span>{record.wbs_code||'ATIVIDADE'}</span><h3>{record.activity_title}</h3><small>{record.record_date}</small></div><dl><div><dt>Executado</dt><dd>{number(record.quantity,3)} {record.unit}</dd></div><div><dt>Equipe</dt><dd>{record.worker_count} pessoa(s)</dd></div><div><dt>Horas</dt><dd>{number(record.worked_hours,1)}h</dd></div><div><dt>Produtividade</dt><dd>{record.productivity_per_labor_hour?`${number(record.productivity_per_labor_hour,3)} ${record.unit}/h-h`:'Sem base'}</dd></div></dl></article>)}{!data.records.length&&<p className="field-empty">Nenhuma produção estruturada registrada.</p>}</div></section>}
    {tab==='occurrences'&&<section className="field-panel"><header><div><span>ACONTECIMENTOS</span><h2>Ocorrências da obra</h2></div><button className="v4-primary" onClick={()=>setShowOccurrence(true)}><Plus size={16}/> Registrar ocorrência</button></header><div className="field-occurrence-list">{data.occurrences.map(item=><article key={item.id}><AlertTriangle size={18}/><div><span>{human(item.occurrence_type)}</span><h3>{item.title}</h3><p>{item.activity_title||'Sem atividade vinculada'}{item.description?` · ${item.description}`:''}</p><small>{item.impact_days?`Impacto informado: ${item.impact_days} dia(s). Aguardando revisão.`:'Sem impacto de prazo informado.'}</small></div></article>)}{!data.occurrences.length&&<p className="field-empty">Nenhuma ocorrência registrada.</p>}</div></section>}
    {showRdo&&<RdoForm busy={busy} close={()=>setShowRdo(false)} save={async body=>{if(await save(`/api/vico/projects/${projectId}/daily-reports`,body,'RDO salvo como rascunho.'))setShowRdo(false)}}/>}
    {showProduction&&<ProductionForm activities={data.activities} reports={data.reports} busy={busy} close={()=>setShowProduction(false)} save={async body=>{if(await save(`/api/vico/projects/${projectId}/productivity`,body,'Produção registrada.'))setShowProduction(false)}}/>}
    {showOccurrence&&<OccurrenceForm activities={data.activities} reports={data.reports} busy={busy} close={()=>setShowOccurrence(false)} save={async body=>{if(await save(`/api/vico/projects/${projectId}/occurrences`,body,'Ocorrência registrada para revisão.'))setShowOccurrence(false)}}/>}
  </div>
}

function Modal({title,children,busy,close,submit}:{title:string;children:any;busy:boolean;close:()=>void;submit:(event:FormEvent)=>void}){return <div className="field-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><header><div><span>REGISTRO DE CAMPO</span><h2>{title}</h2></div><button type="button" onClick={close}>×</button></header>{children}<footer><button type="button" onClick={close}>Cancelar</button><button className="v4-primary" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:null} Salvar</button></footer></form></div>}
function RdoForm({busy,close,save}:{busy:boolean;close:()=>void;save:(body:any)=>void}){const[form,setForm]=useState({reportDate:today(),weather:'',notes:''});return <Modal title="Diário de obra" busy={busy} close={close} submit={e=>{e.preventDefault();save(form)}}><div className="field-form"><label>Data<input required type="date" value={form.reportDate} onChange={e=>setForm({...form,reportDate:e.target.value})}/></label><label>Clima<input value={form.weather} onChange={e=>setForm({...form,weather:e.target.value})} placeholder="Ex.: ensolarado pela manhã; chuva às 16h"/></label><label className="wide">Resumo do dia<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Atividades, materiais, equipamentos, visitantes e observações."/></label></div><p>O RDO será salvo como rascunho e precisará de confirmação humana.</p></Modal>}
function ProductionForm({activities,reports,busy,close,save}:{activities:Activity[];reports:Report[];busy:boolean;close:()=>void;save:(body:any)=>void}){const[form,setForm]=useState({activityId:'',dailyReportId:'',recordDate:today(),quantity:'',unit:'',workedHours:'8',workerCount:'',downtimeHours:'0',downtimeReason:''});function pick(id:string){const activity=activities.find(item=>item.id===Number(id));setForm({...form,activityId:id,unit:activity?.unit||form.unit})}return <Modal title="Apontamento de produção" busy={busy} close={close} submit={e=>{e.preventDefault();save(form)}}><div className="field-form"><label className="wide">Atividade<select required value={form.activityId} onChange={e=>pick(e.target.value)}><option value="">Selecione</option>{activities.map(item=><option key={item.id} value={item.id}>{item.wbs_code?`${item.wbs_code} · `:''}{item.title}</option>)}</select></label><label>RDO relacionado<select value={form.dailyReportId} onChange={e=>setForm({...form,dailyReportId:e.target.value})}><option value="">Sem vínculo</option>{reports.map(item=><option key={item.id} value={item.id}>{item.report_date} · {item.status==='confirmed'?'confirmado':'rascunho'}</option>)}</select></label><label>Data<input required type="date" value={form.recordDate} onChange={e=>setForm({...form,recordDate:e.target.value})}/></label><label>Quantidade<input required type="number" min="0" step="0.001" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Unidade<input required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="m², m³, un."/></label><label>Horas trabalhadas<input required type="number" min="0" step="0.25" value={form.workedHours} onChange={e=>setForm({...form,workedHours:e.target.value})}/></label><label>Nº de trabalhadores<input required type="number" min="0" step="1" value={form.workerCount} onChange={e=>setForm({...form,workerCount:e.target.value})}/></label><label>Horas paradas<input type="number" min="0" step="0.25" value={form.downtimeHours} onChange={e=>setForm({...form,downtimeHours:e.target.value})}/></label><label>Motivo da paralisação<input value={form.downtimeReason} onChange={e=>setForm({...form,downtimeReason:e.target.value})}/></label></div></Modal>}
function OccurrenceForm({activities,reports,busy,close,save}:{activities:Activity[];reports:Report[];busy:boolean;close:()=>void;save:(body:any)=>void}){const[form,setForm]=useState({occurrenceType:'chuva',activityId:'',dailyReportId:'',title:'',description:'',impactDays:'',impactCost:''});return <Modal title="Ocorrência" busy={busy} close={close} submit={e=>{e.preventDefault();save(form)}}><div className="field-form"><label>Tipo<select value={form.occurrenceType} onChange={e=>setForm({...form,occurrenceType:e.target.value})}>{['chuva','falta_material','falta_trabalhador','acidente_incidente','retrabalho','atraso_fornecedor','mudanca_projeto','equipamento_quebrado','interferencia','erro_execucao','paralisacao','outro'].map(item=><option key={item} value={item}>{human(item)}</option>)}</select></label><label>Atividade<select value={form.activityId} onChange={e=>setForm({...form,activityId:e.target.value})}><option value="">Sem vínculo</option>{activities.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>RDO<select value={form.dailyReportId} onChange={e=>setForm({...form,dailyReportId:e.target.value})}><option value="">Sem vínculo</option>{reports.map(item=><option key={item.id} value={item.id}>{item.report_date}</option>)}</select></label><label>Impacto estimado (dias)<input type="number" step="0.5" value={form.impactDays} onChange={e=>setForm({...form,impactDays:e.target.value})}/></label><label className="wide">Título<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><p>O impacto fica registrado para revisão. O cronograma não será alterado automaticamente.</p></Modal>}
