import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, CalendarRange, CheckCircle2, GitBranch, Link2, List, LoaderCircle, LockKeyhole, Plus, RefreshCw, X } from 'lucide-react'

type Activity = {
  id:number; title:string; wbs_code?:string; stage_key:string; discipline:string; priority:string; status:string;
  planned_start?:string; planned_end?:string; duration_days?:number; percent_complete:number|string;
  planned_quantity?:number|string; unit?:string; planned_cost:number|string; readiness:'ready'|'waiting'|'blocked'|'done';
  waiting_on:{id:number;title:string}[]; blockers:Blocker[]; delayed:boolean;
  critical?:boolean; total_float?:number|null;
}
type Dependency = { id:number; predecessor_id:number; successor_id:number; predecessor_title:string; successor_title:string; dependency_type:string; lag_days:number }
type Blocker = { id:number; activity_id:number; blocker_type:string; title:string; description?:string; status:string; due_date?:string; created_by_name?:string }
type Motor = { activities:Activity[]; dependencies:Dependency[]; blockers:Blocker[]; baselines?:any[]; criticalPath?:{valid:boolean;totalDuration:number;criticalIds:number[];nonFsDependencies:number}; nextActions:Activity[]; summary:{total:number;ready:number;blocked:number;waiting:number;delayed:number;scheduled:number}; gantt?:{start:string;end:string;days:number}|null }

async function request(url:string,options:RequestInit={}) { const r=await fetch(url,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro na operação');return d }
const dateValue=(value?:string)=>value?String(value).slice(0,10):''
const label=(value='')=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function MotorPlanning({projectId,staff,notify}:{projectId:number;staff:boolean;notify:(message:string)=>void}) {
  const [data,setData]=useState<Motor|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [mode,setMode]=useState<'gantt'|'list'|'blockers'>('gantt'),[selected,setSelected]=useState<Activity|null>(null)
  const [dependency,setDependency]=useState({predecessorId:'',successorId:'',dependencyType:'FS',lagDays:'0'})
  const [blockerOpen,setBlockerOpen]=useState(false)
  async function load(){setError('');try{setData(await request(`/api/vico/projects/${projectId}/motor`))}catch(e:any){setError(e.message)}}
  useEffect(()=>{setData(null);setSelected(null);load()},[projectId])
  async function mutate(url:string,options:RequestInit,message:string){setBusy(true);try{await request(url,options);await load();window.dispatchEvent(new CustomEvent('obra360:refresh'));notify(message);return true}catch(e:any){notify(e.message);return false}finally{setBusy(false)}}
  async function baseline(){const name=`Baseline ${new Date().toLocaleDateString('pt-BR')}`;await mutate(`/api/vico/projects/${projectId}/baselines`,{method:'POST',body:JSON.stringify({name})},'Baseline registrada sem alterar o cronograma atual.')}
  const range=useMemo(()=>data?.gantt?{start:new Date(`${data.gantt.start}T12:00:00`),days:data.gantt.days}:null,[data?.gantt])
  function bar(activity:Activity){if(!range||!activity.planned_start||!activity.planned_end)return null;const start=Math.max(0,Math.round((new Date(`${dateValue(activity.planned_start)}T12:00:00`).getTime()-range.start.getTime())/86400000));const duration=Math.max(1,Number(activity.duration_days)||1);return {left:`${start/range.days*100}%`,width:`${Math.max(1.5,duration/range.days*100)}%`}}
  if(error)return <div className="v4-page"><div className="v4-form-error">{error}</div><button className="v4-primary" onClick={load}><RefreshCw size={16}/> Tentar novamente</button></div>
  if(!data)return <div className="v4-loading">Carregando Motor da Obra…</div>
  const activeBlockers=data.blockers.filter(item=>item.status==='active')
  return <div className="v4-page motor-page">
    <header className="motor-head"><div><span>MOTOR DA OBRA · PLANEJAMENTO</span><h1>Atividades, dependências e bloqueios.</h1><p>O sistema diferencia o que está pronto para começar, o que aguarda predecessoras e o que possui impedimentos registrados.</p></div><div>{staff&&<button className="v4-outline" disabled={busy} onClick={baseline}><GitBranch size={16}/> Registrar baseline</button>}<button className="v4-outline" onClick={load}><RefreshCw size={16}/> Atualizar</button></div></header>
    <section className="motor-summary"><article><CalendarRange/><span><b>{data.summary.scheduled}</b><small>programadas</small></span></article><article><CheckCircle2/><span><b>{data.summary.ready}</b><small>prontas</small></span></article><article><GitBranch/><span><b>{data.summary.waiting}</b><small>aguardando</small></span></article><article className={data.summary.blocked?'danger':''}><LockKeyhole/><span><b>{data.summary.blocked}</b><small>bloqueadas</small></span></article><article className={data.summary.delayed?'danger':''}><AlertTriangle/><span><b>{data.summary.delayed}</b><small>atrasadas</small></span></article><article><GitBranch/><span><b>{data.criticalPath?.criticalIds?.length||0}</b><small>no caminho crítico</small></span></article></section>
    <div className="motor-tabs"><button className={mode==='gantt'?'active':''} onClick={()=>setMode('gantt')}><CalendarRange size={16}/> Gantt</button><button className={mode==='list'?'active':''} onClick={()=>setMode('list')}><List size={16}/> Lista</button><button className={mode==='blockers'?'active':''} onClick={()=>setMode('blockers')}><LockKeyhole size={16}/> Bloqueios <em>{activeBlockers.length}</em></button></div>
    {mode==='gantt'&&<section className="motor-panel"><header><div><span>CRONOGRAMA</span><h2>Previsto e prontidão operacional</h2></div><small>{data.gantt?`${dateValue(data.gantt.start)} → ${dateValue(data.gantt.end)} · rede ${data.criticalPath?.totalDuration||0}d`:'Cadastre datas nas atividades para formar o Gantt.'}</small></header><div className="motor-gantt">{data.activities.map(activity=><button key={activity.id} onClick={()=>setSelected(activity)} className={`motor-gantt-row ${activity.readiness} ${activity.critical?'critical':''}`}><div><strong>{activity.wbs_code||'—'}</strong><span>{activity.title}{activity.critical&&<em>CRÍTICA</em>}</span><small>{activity.planned_start?`${dateValue(activity.planned_start)} → ${dateValue(activity.planned_end)}`:'Sem programação'}{activity.total_float!==null&&activity.total_float!==undefined?` · folga ${activity.total_float}d`:''}</small></div><i>{bar(activity)&&<em style={bar(activity)!}><span style={{width:`${Number(activity.percent_complete)||0}%`}}/></em>}</i></button>)}</div><p className="motor-empty">Caminho crítico calculado pela rede de precedência e duração. Dependências não-FS ({data.criticalPath?.nonFsDependencies||0}) exigem conferência no planejamento detalhado.</p></section>}
    {mode==='list'&&<section className="motor-panel"><header><div><span>ATIVIDADES</span><h2>Lista operacional</h2></div></header><div className="motor-table"><div className="motor-table-head"><span>WBS / Atividade</span><span>Período</span><span>Situação</span><span>Avanço</span></div>{data.activities.map(activity=><button key={activity.id} onClick={()=>setSelected(activity)}><span><b>{activity.wbs_code||'—'}</b>{activity.title}</span><span>{activity.planned_start?`${dateValue(activity.planned_start)} a ${dateValue(activity.planned_end)}`:'Não programada'}</span><span className={`motor-state ${activity.readiness}`}>{activity.readiness==='ready'?'Pronta':activity.readiness==='waiting'?'Aguardando':activity.readiness==='blocked'?'Bloqueada':'Concluída'}</span><span>{Number(activity.percent_complete)||0}%</span></button>)}</div></section>}
    {mode==='blockers'&&<section className="motor-panel"><header><div><span>IMPEDIMENTOS</span><h2>Bloqueios ativos</h2></div>{staff&&<button className="v4-primary" onClick={()=>setBlockerOpen(true)}><Plus size={16}/> Registrar bloqueio</button>}</header><div className="motor-blockers">{activeBlockers.map(item=>{const activity=data.activities.find(a=>a.id===item.activity_id);return <article key={item.id}><LockKeyhole size={18}/><div><span>{label(item.blocker_type)}</span><h3>{item.title}</h3><p>{activity?.title||'Atividade'}{item.description?` · ${item.description}`:''}</p></div>{staff&&<button disabled={busy} onClick={()=>mutate(`/api/vico/projects/${projectId}/blockers/${item.id}/resolve`,{method:'PATCH'},'Bloqueio marcado como resolvido.')}><CheckCircle2 size={16}/> Resolver</button>}</article>})}{!activeBlockers.length&&<p className="motor-empty">Nenhum bloqueio ativo registrado. Isso não substitui inspeção ou liberação técnica.</p>}</div></section>}
    <div className="motor-bottom"><section className="motor-panel"><header><div><span>PRÓXIMA AÇÃO</span><h2>Atividades liberadas pelo grafo</h2></div></header>{data.nextActions.slice(0,5).map((activity,index)=><button className="motor-next" key={activity.id} onClick={()=>setSelected(activity)}><b>{String(index+1).padStart(2,'0')}</b><span><strong>{activity.title}</strong><small>{label(activity.stage_key)} · prioridade {label(activity.priority)}</small></span><ArrowRight size={16}/></button>)}{!data.nextActions.length&&<p className="motor-empty">Nenhuma atividade pendente está livre de dependências e bloqueios.</p>}</section>{staff&&<DependencyForm data={data} value={dependency} setValue={setDependency} busy={busy} save={()=>mutate(`/api/vico/projects/${projectId}/dependencies`,{method:'POST',body:JSON.stringify(dependency)},'Dependência registrada.')} remove={id=>mutate(`/api/vico/projects/${projectId}/dependencies/${id}`,{method:'DELETE'},'Dependência removida.')}/>}</div>
    {selected&&<ActivityEditor activity={selected} busy={busy} close={()=>setSelected(null)} save={async body=>{if(await mutate(`/api/vico/projects/${projectId}/activities/${selected.id}`,{method:'PATCH',body:JSON.stringify(body)},'Planejamento da atividade atualizado.'))setSelected(null)}}/>} 
    {blockerOpen&&<BlockerForm activities={data.activities} busy={busy} close={()=>setBlockerOpen(false)} save={async body=>{if(await mutate(`/api/vico/projects/${projectId}/blockers`,{method:'POST',body:JSON.stringify(body)},'Bloqueio registrado.'))setBlockerOpen(false)}}/>} 
  </div>
}

function ActivityEditor({activity,busy,close,save}:{activity:Activity;busy:boolean;close:()=>void;save:(body:any)=>Promise<void>}){
  const[form,setForm]=useState({wbsCode:activity.wbs_code||'',plannedStart:dateValue(activity.planned_start),plannedEnd:dateValue(activity.planned_end),percentComplete:String(activity.percent_complete||0),plannedQuantity:String(activity.planned_quantity||''),unit:activity.unit||'',plannedCost:String(activity.planned_cost||0)})
  function submit(e:FormEvent){e.preventDefault();save(form)}
  return <div className="motor-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><header><div><span>PLANEJAR ATIVIDADE</span><h2>{activity.title}</h2></div><button type="button" aria-label="Fechar" onClick={close}><X size={18}/></button></header><div className="motor-form-grid"><label>WBS<input value={form.wbsCode} onChange={e=>setForm({...form,wbsCode:e.target.value})} placeholder="Ex.: 3.2.1"/></label><label>Início planejado<input type="date" value={form.plannedStart} onChange={e=>setForm({...form,plannedStart:e.target.value})}/></label><label>Fim planejado<input type="date" value={form.plannedEnd} onChange={e=>setForm({...form,plannedEnd:e.target.value})}/></label><label>Avanço informado (%)<input type="number" min="0" max="100" value={form.percentComplete} onChange={e=>setForm({...form,percentComplete:e.target.value})}/></label><label>Quantidade prevista<input type="number" min="0" step="0.001" value={form.plannedQuantity} onChange={e=>setForm({...form,plannedQuantity:e.target.value})}/></label><label>Unidade<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="m², m³, un."/></label><label>Custo planejado<input type="number" min="0" step="0.01" value={form.plannedCost} onChange={e=>setForm({...form,plannedCost:e.target.value})}/></label></div><p>O avanço é um registro humano. Datas e percentuais não são recalculados silenciosamente.</p><footer><button type="button" onClick={close}>Cancelar</button><button className="v4-primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:null} Salvar planejamento</button></footer></form></div>
}

function DependencyForm({data,value,setValue,busy,save,remove}:{data:Motor;value:any;setValue:(value:any)=>void;busy:boolean;save:()=>void;remove:(id:number)=>void}){
  return <section className="motor-panel motor-dependency"><header><div><span>GRAFO</span><h2>Dependências</h2></div><Link2 size={20}/></header><div className="motor-dependency-form"><label>Predecessora<select value={value.predecessorId} onChange={e=>setValue({...value,predecessorId:e.target.value})}><option value="">Selecione</option>{data.activities.map(a=><option key={a.id} value={a.id}>{a.wbs_code?`${a.wbs_code} · `:''}{a.title}</option>)}</select></label><label>Sucessora<select value={value.successorId} onChange={e=>setValue({...value,successorId:e.target.value})}><option value="">Selecione</option>{data.activities.map(a=><option key={a.id} value={a.id}>{a.wbs_code?`${a.wbs_code} · `:''}{a.title}</option>)}</select></label><div><label>Tipo<select value={value.dependencyType} onChange={e=>setValue({...value,dependencyType:e.target.value})}><option value="FS">Término → início</option><option value="SS">Início → início</option><option value="FF">Término → término</option><option value="SF">Início → término</option></select></label><label>Defasagem<input type="number" value={value.lagDays} onChange={e=>setValue({...value,lagDays:e.target.value})}/></label></div><button className="v4-primary" disabled={busy||!value.predecessorId||!value.successorId} onClick={save}><Plus size={16}/> Adicionar dependência</button></div><div className="motor-dependency-list">{data.dependencies.map(item=><div key={item.id}><span><b>{item.predecessor_title}</b><ArrowRight size={14}/><b>{item.successor_title}</b><small>{item.dependency_type}{item.lag_days?` · ${item.lag_days}d`:''}</small></span><button aria-label="Remover dependência" onClick={()=>remove(item.id)}><X size={15}/></button></div>)}{!data.dependencies.length&&<p>Nenhuma dependência cadastrada.</p>}</div></section>
}

function BlockerForm({activities,busy,close,save}:{activities:Activity[];busy:boolean;close:()=>void;save:(body:any)=>Promise<void>}){
  const[form,setForm]=useState({activityId:'',blockerType:'material',title:'',description:'',dueDate:''})
  function submit(e:FormEvent){e.preventDefault();save(form)}
  return <div className="motor-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><header><div><span>REGISTRAR IMPEDIMENTO</span><h2>Bloqueio da atividade</h2></div><button type="button" aria-label="Fechar" onClick={close}><X size={18}/></button></header><div className="motor-form-grid"><label>Atividade<select required value={form.activityId} onChange={e=>setForm({...form,activityId:e.target.value})}><option value="">Selecione</option>{activities.filter(a=>a.status!=='done').map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label>Tipo<select value={form.blockerType} onChange={e=>setForm({...form,blockerType:e.target.value})}>{['predecessora','projeto','documento','aprovacao','cliente','material','equipamento','mao_de_obra','sst','fornecedor','inspecao','decisao','outro'].map(type=><option key={type} value={type}>{label(type)}</option>)}</select></label><label>Motivo<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Prazo para resolver<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label className="wide">Detalhes<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><footer><button type="button" onClick={close}>Cancelar</button><button className="v4-primary" disabled={busy}>Registrar bloqueio</button></footer></form></div>
}
