import {useEffect,useState} from 'react'
import {CheckCircle2,Landmark,LoaderCircle,Plus,ShieldAlert} from 'lucide-react'

async function api(url:string,options:RequestInit={}){const r=await fetch(url,{...options,credentials:'include',headers:{'Content-Type':'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erro na operação');return d}
const labels:Record<string,string>={pending:'Pendente',in_progress:'Em andamento',requirement:'Exigência',approved:'Aprovada',not_applicable:'Não se aplica'}

export default function MunicipalWorkflow({projectId,staff,notify}:{projectId:number;staff:boolean;notify:(message:string)=>void}){
  const[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false)
  async function load(){setData(await api(`/api/vico/projects/${projectId}/municipal`))}
  useEffect(()=>{load().catch(e=>notify(e.message))},[projectId])
  async function act(url:string,body:any,method='POST'){setBusy(true);try{await api(url,{method,body:JSON.stringify(body)});await load();notify('Fluxo administrativo atualizado.')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
  if(!data)return <div className="v4-loading">Carregando fluxo administrativo…</div>
  return <div className="v4-page municipal-page">
    <header><div><span>BUROCRACIA CONFIGURÁVEL</span><h1>O fluxo público sem regras inventadas.</h1><p>A empresa registra etapas confirmadas em fonte oficial e aplica o roteiro adequado à obra. A VIÇO acompanha protocolos e exigências, mas não presume conformidade ou aprovação legal.</p></div>{staff&&<button className="v4-primary" onClick={()=>setCreating(!creating)}><Plus size={16}/> Novo modelo verificado</button>}</header>
    <section className="municipal-summary"><article><Landmark/><div><b>{data.summary.total}</b><span>etapas aplicadas</span></div></article><article><CheckCircle2/><div><b>{data.summary.approved}</b><span>aprovadas</span></div></article><article className={data.summary.requirements?'danger':''}><ShieldAlert/><div><b>{data.summary.requirements}</b><span>exigências</span></div></article></section>
    {staff&&creating&&<WorkflowForm project={data.project} busy={busy} close={()=>setCreating(false)} save={(body:any)=>act(`/api/vico/projects/${projectId}/municipal/workflows`,body).then(()=>setCreating(false))}/>} 
    {staff&&<section className="municipal-templates"><div><span>MODELOS DA EMPRESA</span><h2>Aplicar roteiro à obra</h2></div><div>{data.templates.map((item:any)=><article key={item.id}><div><b>{item.name}</b><small>{item.municipality}/{item.state_code} · {item.step_count} etapas · {item.project_kind}</small></div><button disabled={busy} onClick={()=>act(`/api/vico/projects/${projectId}/municipal/apply`,{workflowId:item.id})}>Aplicar</button></article>)}{!data.templates.length&&<p>Cadastre um modelo somente depois de confirmar as etapas em fonte oficial.</p>}</div></section>}
    <section className="municipal-flow"><header><span>ACOMPANHAMENTO DA OBRA</span><h2>Protocolos, exigências e aprovações</h2></header>{data.steps.map((item:any,index:number)=><AdministrativeStep key={item.id} item={item} index={index} staff={staff} busy={busy} save={(body:any)=>act(`/api/vico/projects/${projectId}/municipal/steps/${item.id}`,body,'PATCH')}/>) }{!data.steps.length&&<div className="municipal-empty"><Landmark/><h3>Nenhum fluxo aplicado</h3><p>Aplique um modelo verificado para acompanhar esta obra.</p></div>}</section>
  </div>
}

function WorkflowForm({project,busy,close,save}:{project:any;busy:boolean;close:()=>void;save:(body:any)=>void}){const[form,setForm]=useState({municipality:project.city||'',stateCode:'MG',projectKind:project.kind||'obra',name:'',steps:''});return <section className="municipal-create"><div><span>BASE VERIFICADA</span><h2>Novo modelo municipal</h2><p>Transcreva somente etapas confirmadas no portal ou orientação oficial do município. Uma etapa por linha.</p></div><div className="municipal-create-grid"><label>Município<input value={form.municipality} onChange={e=>setForm({...form,municipality:e.target.value})}/></label><label>UF<input maxLength={2} value={form.stateCode} onChange={e=>setForm({...form,stateCode:e.target.value.toUpperCase()})}/></label><label>Tipo de obra<input value={form.projectKind} onChange={e=>setForm({...form,projectKind:e.target.value})}/></label><label>Nome do modelo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Residencial — fluxo confirmado"/></label><label className="wide">Etapas<textarea value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})} placeholder={'Documentação inicial\nProtocolo\nAnálise\nAlvará'}/></label></div><footer><button onClick={close}>Cancelar</button><button className="v4-primary" disabled={busy} onClick={()=>save({...form,steps:form.steps.split('\n')})}>{busy?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>} Salvar modelo</button></footer></section>}

function AdministrativeStep({item,index,staff,busy,save}:{item:any;index:number;staff:boolean;busy:boolean;save:(body:any)=>void}){const[editing,setEditing]=useState(false),[form,setForm]=useState({status:item.status,protocolNumber:item.protocol_number||'',notes:item.notes||''});return <article className={`municipal-step status-${item.status}`}><div className="municipal-step-index">{String(index+1).padStart(2,'0')}</div><div className="municipal-step-main"><span>{item.workflow_name} · {item.municipality}/{item.state_code}</span><h3>{item.title}</h3><p>{item.notes||'Sem observações registradas.'}</p>{item.protocol_number&&<small>Protocolo: {item.protocol_number}</small>}</div><strong>{labels[item.status]||item.status}</strong>{staff&&<button onClick={()=>setEditing(!editing)}>{editing?'Fechar':'Atualizar'}</button>}{editing&&<div className="municipal-step-edit"><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Protocolo<input value={form.protocolNumber} onChange={e=>setForm({...form,protocolNumber:e.target.value})}/></label><label className="wide">Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="v4-primary" disabled={busy} onClick={()=>save(form)}>Salvar atualização</button></div>}</article>}
