import { useState } from 'react'
import { ArrowRight, Camera, ClipboardCheck, FileSearch, ListChecks, Mic, ShieldCheck, WalletCards } from 'lucide-react'
import { pendingActions, checklistProgress, type ActionItem } from './operation-summary'

type Data = {
  project: { name: string; city?: string; budget: number|string; spent: number|string; committed?: number|string };
  tasks: ActionItem[];
  stages: { key: string; title: string; applicable: number; done: number; progress: number }[];
  photos: { id: number; data_url: string; caption?: string; task_title?: string; created_at: string }[];
  events: { id?: number; title?: string; description?: string; created_at?: string }[];
}
const money = (value: number|string|undefined) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(Number(value) || 0)
const day = (value?: string) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleDateString('pt-BR') : 'Data não informada'

export default function VicoOverview({ b, staff, openStage, openCopilot, setView }: {
  b: Data; staff: boolean; openStage: (key: string) => void;
  openCopilot: (tab?: 'voice'|'vision'|'report') => void;
  setView: (view: 'roadmap'|'photos'|'safety'|'finance') => void;
}) {
  const [filter, setFilter] = useState('all')
  const pending = pendingActions(b.tasks, !staff)
  const actions = pending.filter(t => filter === 'all' || (filter === 'client' ? t.client_action : t.discipline === 'sst'))
  const progress = checklistProgress(b.tasks)
  const current = b.stages.find(s => s.applicable > s.done)
  const decisions = pendingActions(b.tasks, true).length
  const safety = b.tasks.filter(t => t.status === 'pending' && t.discipline === 'sst').length
  return <div className="v4-page vico-overview">
    <header className="vico-page-heading"><div><span className="vico-eyebrow">{staff ? 'CENTRAL DA OBRA' : 'MINHA OBRA'}</span><h1>{b.project.name}</h1><p>{b.project.city || 'Município não informado'} · Informação para decidir, registro para acompanhar.</p></div><button className="v4-outline" onClick={() => openCopilot('report')}><ClipboardCheck size={17}/> Relatório</button></header>
    <section className="vico-focus"><div><span className="vico-eyebrow">{staff ? 'O QUE PRECISA DA SUA ATENÇÃO' : 'DECISÕES QUE DEPENDEM DE VOCÊ'}</span><h2>{pending[0]?.title || (staff ? 'Nenhum item pendente no roteiro.' : 'Nenhuma decisão aguardando você.')}</h2><p>{pending[0]?.detail || 'Acompanhe os registros recentes e converse com a equipe quando precisar.'}</p>{pending[0] && <button onClick={() => openStage(pending[0].stage_key)}>Revisar na etapa <ArrowRight size={17}/></button>}<small>Ordem por prioridade cadastrada. Não representa liberação para executar.</small></div><aside><b>{progress.percent}<span>%</span></b><strong>do checklist concluído</strong><p>{progress.done} de {progress.applicable} itens aplicáveis</p><div className="vico-progress-track"><i style={{ width: `${progress.percent}%` }}/></div><small>Não equivale ao avanço físico da obra.</small></aside></section>
    <section className="vico-quick" aria-label="Ações rápidas"><button onClick={() => openCopilot('voice')}><Mic size={20}/><span>Registrar por voz</span></button><button onClick={() => setView('photos')}><Camera size={20}/><span>Fotos do canteiro</span></button><button onClick={() => setView('roadmap')}><ListChecks size={20}/><span>Etapas e checklist</span></button><button onClick={() => openCopilot('vision')}><FileSearch size={20}/><span>Analisar documento</span></button></section>
    <div className="vico-work-grid"><section className="vico-panel"><header><div><span className="vico-eyebrow">{staff ? 'PRÓXIMAS AÇÕES' : 'SUAS PENDÊNCIAS'}</span><h2>Prioridades registradas <span className="vico-count">{actions.length}</span></h2></div></header>{staff && <div className="vico-filters" aria-label="Filtrar pendências">{[['all','Todas'],['client','Cliente'],['safety','SST']].map(([key,label]) => <button key={key} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}</button>)}</div>}<div className="vico-action-list">{actions.slice(0,8).map((task,index) => <button key={task.id} onClick={() => openStage(task.stage_key)}><span className="vico-action-number">{String(index+1).padStart(2,'0')}</span><div><strong>{task.title}</strong><small>{b.stages.find(s => s.key === task.stage_key)?.title || 'Etapa'} · {task.client_action ? 'Ação do proprietário' : 'Equipe técnica'}</small></div><span className={`vico-priority ${task.priority}`}>{({critica:'Crítica',alta:'Alta',normal:'Normal',baixa:'Baixa'} as Record<string,string>)[task.priority] || 'Normal'}</span><ArrowRight size={16}/></button>)}</div>{!actions.length && <p className="vico-empty">Nenhum item pendente neste filtro. Isso não comprova conformidade técnica ou de SST.</p>}{actions.length>8 && <p className="vico-note">Exibindo 8 de {actions.length} itens. Consulte os demais em Etapas e checklist.</p>}</section>
    <aside className="vico-side-summary"><section className="vico-panel"><span className="vico-eyebrow">RESUMO DO ROTEIRO</span><h3>{current?.title || 'Sem etapa pendente no checklist'}</h3><p>Primeira etapa com itens em aberto; confirme a frente em execução com a equipe.</p><dl><div><dt>Prazo da obra</dt><dd>Não calculado</dd></div><div><dt>Avanço físico</dt><dd>Sem medição estruturada</dd></div><div><dt>Decisões do cliente</dt><dd>{decisions} pendente(s)</dd></div></dl></section><section className="vico-panel"><span className="vico-eyebrow">CUSTOS REGISTRADOS</span><h3>{money(b.project.spent)}</h3><p>Realizado no cadastro da obra</p><dl><div><dt>Orçamento</dt><dd>{Number(b.project.budget)>0 ? money(b.project.budget) : 'Não informado'}</dd></div><div><dt>Comprometido</dt><dd>{money(b.project.committed)}</dd></div></dl><button className="vico-text-button" onClick={() => setView('finance')}><WalletCards size={16}/> Consultar custos <ArrowRight size={16}/></button></section>{staff && <section className="vico-safety"><ShieldCheck size={22}/><div><strong>{safety} pendência(s) de SST</strong><p>Itens do roteiro, não uma avaliação automática de segurança.</p><button onClick={() => setView('safety')}>Revisar pendências →</button></div></section>}</aside></div>
    <div className="vico-bottom-grid"><section className="vico-panel"><header><div><span className="vico-eyebrow">EVIDÊNCIAS</span><h2>Últimos registros visuais</h2></div><button className="vico-text-button" onClick={() => setView('photos')}>Ver fotos <ArrowRight size={16}/></button></header>{b.photos.length ? <div className="vico-photo-grid">{b.photos.slice(0,3).map(photo => <button key={photo.id} onClick={() => setView('photos')}><img src={photo.data_url} alt={photo.caption || photo.task_title || 'Registro da obra'} loading="lazy"/><strong>{photo.task_title || photo.caption || 'Registro visual'}</strong><small>{day(photo.created_at)}</small></button>)}</div> : <p className="vico-empty">Ainda não há fotos nesta obra. Registre uma evidência do canteiro para começar.</p>}</section><section className="vico-panel"><span className="vico-eyebrow">HISTÓRICO DA OBRA</span><h2>Últimos acontecimentos</h2><ol className="vico-timeline">{b.events.slice(0,5).map((event,index) => <li key={event.id ?? index}><small>{day(event.created_at)}</small><strong>{event.title || 'Registro da obra'}</strong></li>)}</ol>{!b.events.length && <p className="vico-empty">Nenhum acontecimento registrado ainda.</p>}</section></div>
    <footer className="vico-page-footer">VIÇO · Engenharia, dados e inteligência para o canteiro.<span>Decisões técnicas permanecem com o profissional responsável.</span></footer>
  </div>
}
