import express from 'express'
import cookieParser from 'cookie-parser'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import pg from 'pg'
import path from 'path'
import {fileURLToPath} from 'url'

const {Pool}=pg
const __dirname=path.dirname(fileURLToPath(import.meta.url))
const PORT=Number(process.env.PORT||10000)
const DATABASE_URL=process.env.DATABASE_URL
const JWT_SECRET=process.env.JWT_SECRET||'change-me'
const COOKIE='obra360_session'
const OPENAI_API_KEY=process.env.OPENAI_API_KEY
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-terra'
if(!DATABASE_URL){console.error('DATABASE_URL ausente');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}})

const DEFAULT_PHASES=['Pré-obra e projetos','Terraplenagem e fundações','Estrutura','Vedações e cobertura','Instalações','Impermeabilização e revestimentos','Acabamentos','Vistoria e entrega']
const REQUIREMENTS={
  'Pré-obra e projetos':[
    ['documento','Projetos e escopo aplicáveis definidos',true],['responsabilidade','Responsabilidades técnicas registradas conforme escopo',true],['legal','Licenças e aprovações aplicáveis verificadas',true],['seguranca','Planejamento inicial de SST e requisitos aplicáveis avaliados',true]
  ],
  'Terraplenagem e fundações':[
    ['tecnico','Condição do terreno e locação verificadas',true],['tecnico','Sondagem / solução de fundação verificada quando aplicável',true],['evidencia','Armaduras, formas e cotas registradas antes do fechamento/concretagem',true],['seguranca','Acessos, escavações e proteções avaliados',true],['medicao','Medição da etapa registrada',false]
  ],
  'Estrutura':[
    ['tecnico','Projeto estrutural e revisão aplicável disponíveis',true],['evidencia','Armaduras, formas e pontos críticos registrados antes da concretagem',true],['qualidade','Concretagem / execução registrada',true],['seguranca','Proteções coletivas e riscos de queda avaliados',true],['medicao','Medição da estrutura registrada',false]
  ],
  'Vedações e cobertura':[
    ['tecnico','Locação de paredes e aberturas conferida',true],['evidencia','Cobertura e interfaces críticas registradas',true],['seguranca','Riscos de trabalho em altura e proteção coletiva avaliados',true],['qualidade','Pendências de prumo, nível e vedação tratadas',false]
  ],
  'Instalações':[
    ['projeto','Projetos / definições de instalações disponíveis',true],['evidencia','Tubulações e eletrodutos fotografados antes do fechamento',true],['qualidade','Testes aplicáveis registrados',true],['seguranca','Riscos elétricos e interferências avaliados',true]
  ],
  'Impermeabilização e revestimentos':[
    ['qualidade','Base e preparação verificadas',true],['evidencia','Impermeabilizações críticas registradas antes do revestimento',true],['qualidade','Testes de estanqueidade quando aplicáveis registrados',true],['medicao','Medição da etapa registrada',false]
  ],
  'Acabamentos':[
    ['qualidade','Amostras / especificações aprovadas',false],['evidencia','Execução e correções registradas',true],['qualidade','Checklist de acabamento atualizado',true]
  ],
  'Vistoria e entrega':[
    ['qualidade','Vistoria final e pendências registradas',true],['documento','Dossiê e documentos finais organizados',true],['passaporte','Passaporte técnico do imóvel revisado',true],['garantia','Garantias e orientações de manutenção registradas',true]
  ]
}

async function migrate(){
  const c=await pool.connect();try{await c.query('BEGIN');await c.query(`
    CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'client',created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS projects(id SERIAL PRIMARY KEY,name TEXT NOT NULL,city TEXT,address TEXT,client_name TEXT,status TEXT NOT NULL DEFAULT 'planejamento',start_date DATE,planned_end_date DATE,budget NUMERIC(14,2) DEFAULT 0,committed NUMERIC(14,2) DEFAULT 0,spent NUMERIC(14,2) DEFAULT 0,progress NUMERIC(5,2) DEFAULT 0,planned_progress NUMERIC(5,2) DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS project_members(project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,member_role TEXT DEFAULT 'client',PRIMARY KEY(project_id,user_id));
    CREATE TABLE IF NOT EXISTS phases(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,order_index INTEGER DEFAULT 0,status TEXT DEFAULT 'nao_iniciada',planned_progress NUMERIC(5,2) DEFAULT 0,actual_progress NUMERIC(5,2) DEFAULT 0,planned_start DATE,planned_end DATE,actual_start DATE,actual_end DATE,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS project_events(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,event_type TEXT DEFAULT 'atualizacao',title TEXT NOT NULL,description TEXT,happened_at TIMESTAMPTZ DEFAULT now(),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,metadata JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS phase_gates(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,phase_id INTEGER REFERENCES phases(id) ON DELETE SET NULL,phase_name TEXT NOT NULL,order_index INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft',technical_score INTEGER DEFAULT 0,notes TEXT,released_at TIMESTAMPTZ,released_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(project_id,order_index));
    CREATE TABLE IF NOT EXISTS gate_requirements(id SERIAL PRIMARY KEY,gate_id INTEGER REFERENCES phase_gates(id) ON DELETE CASCADE,category TEXT NOT NULL,title TEXT NOT NULL,required BOOLEAN DEFAULT true,status TEXT NOT NULL DEFAULT 'pendente',notes TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS gate_evidence(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,gate_id INTEGER REFERENCES phase_gates(id) ON DELETE CASCADE,requirement_id INTEGER REFERENCES gate_requirements(id) ON DELETE SET NULL,evidence_type TEXT NOT NULL,title TEXT NOT NULL,description TEXT,url TEXT,captured_at TIMESTAMPTZ DEFAULT now(),created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS payment_releases(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,gate_id INTEGER REFERENCES phase_gates(id) ON DELETE SET NULL,description TEXT NOT NULL,claimed_amount NUMERIC(14,2) DEFAULT 0,validated_amount NUMERIC(14,2) DEFAULT 0,recommendation TEXT NOT NULL DEFAULT 'hold',reason TEXT,status TEXT NOT NULL DEFAULT 'pending',created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,decided_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),decided_at TIMESTAMPTZ);
    CREATE TABLE IF NOT EXISTS passport_items(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,system_type TEXT NOT NULL,zone TEXT,title TEXT NOT NULL,description TEXT,photo_url TEXT,height_cm NUMERIC(10,2),depth_cm NUMERIC(10,2),warranty_until DATE,supplier TEXT,metadata JSONB DEFAULT '{}'::jsonb,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS safety_items(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,title TEXT NOT NULL,category TEXT DEFAULT 'inspecao',severity TEXT DEFAULT 'media',status TEXT DEFAULT 'aberta',due_date DATE,standard_ref TEXT,description TEXT,responsible TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
    CREATE INDEX IF NOT EXISTS idx_pass_gates_project ON phase_gates(project_id,order_index);
    CREATE INDEX IF NOT EXISTS idx_pass_requirements_gate ON gate_requirements(gate_id);
    CREATE INDEX IF NOT EXISTS idx_pass_evidence_gate ON gate_evidence(gate_id);
    CREATE INDEX IF NOT EXISTS idx_passport_project ON passport_items(project_id);
  `);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
  const email=process.env.ADMIN_EMAIL,password=process.env.ADMIN_PASSWORD,name=process.env.ADMIN_NAME||'Equipe Obra360';if(email&&password){const hash=await bcrypt.hash(password,12);await pool.query(`INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'admin') ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,role='admin'`,[name,email.toLowerCase(),hash])}
}

function auth(req,res,next){const token=req.cookies[COOKIE];if(!token)return res.status(401).json({error:'Não autenticado'});try{req.user=jwt.verify(token,JWT_SECRET);next()}catch{return res.status(401).json({error:'Sessão expirada'})}}
function staff(req,res,next){if(!['admin','team'].includes(req.user?.role))return res.status(403).json({error:'Acesso restrito à equipe técnica'});next()}
async function access(user,projectId){if(['admin','team'].includes(user.role))return true;const q=await pool.query('SELECT 1 FROM project_members WHERE project_id=$1 AND user_id=$2',[projectId,user.id]);return q.rowCount>0}
const num=v=>Number(v)||0

async function seedGates(projectId){
  const gateCount=await pool.query('SELECT count(*)::int c FROM phase_gates WHERE project_id=$1',[projectId]);if(gateCount.rows[0].c>0)return
  let phases=(await pool.query('SELECT * FROM phases WHERE project_id=$1 ORDER BY order_index,id',[projectId])).rows
  if(!phases.length){for(let i=0;i<DEFAULT_PHASES.length;i++){const r=await pool.query('INSERT INTO phases(project_id,name,order_index,status) VALUES($1,$2,$3,$4) RETURNING *',[projectId,DEFAULT_PHASES[i],i+1,i===0?'em_andamento':'nao_iniciada']);phases.push(r.rows[0])}}
  for(let i=0;i<phases.length;i++){
    const phase=phases[i];const status=i===0?'pending_review':'draft';const g=(await pool.query('INSERT INTO phase_gates(project_id,phase_id,phase_name,order_index,status) VALUES($1,$2,$3,$4,$5) RETURNING *',[projectId,phase.id,phase.name,phase.order_index||i+1,status])).rows[0]
    const reqs=REQUIREMENTS[phase.name]||[['tecnico','Critérios técnicos da etapa definidos pela equipe',true],['evidencia','Evidências de execução registradas',true],['seguranca','Condições de segurança verificadas',true]]
    for(const [category,title,required] of reqs)await pool.query('INSERT INTO gate_requirements(gate_id,category,title,required) VALUES($1,$2,$3,$4)',[g.id,category,title,required])
  }
}

async function getPass(projectId){
  await seedGates(projectId)
  const [pq,gq,rq,eq,payq,passq,sq]=await Promise.all([
    pool.query('SELECT * FROM projects WHERE id=$1',[projectId]),
    pool.query(`SELECT g.*,u.name released_by_name FROM phase_gates g LEFT JOIN users u ON u.id=g.released_by WHERE g.project_id=$1 ORDER BY g.order_index`,[projectId]),
    pool.query(`SELECT r.*,COUNT(e.id)::int evidence_count FROM gate_requirements r JOIN phase_gates g ON g.id=r.gate_id LEFT JOIN gate_evidence e ON e.requirement_id=r.id WHERE g.project_id=$1 GROUP BY r.id ORDER BY r.id`,[projectId]),
    pool.query('SELECT gate_id,COUNT(*)::int c FROM gate_evidence WHERE project_id=$1 GROUP BY gate_id',[projectId]),
    pool.query('SELECT * FROM payment_releases WHERE project_id=$1 ORDER BY created_at DESC',[projectId]),
    pool.query('SELECT * FROM passport_items WHERE project_id=$1 ORDER BY created_at DESC',[projectId]),
    pool.query(`SELECT * FROM safety_items WHERE project_id=$1 AND lower(status) NOT IN ('resolvida','concluida','fechada') ORDER BY updated_at DESC`,[projectId])
  ])
  const project=pq.rows[0];if(!project)return null
  const reqBy=new Map();for(const r of rq.rows){if(!reqBy.has(r.gate_id))reqBy.set(r.gate_id,[]);reqBy.get(r.gate_id).push(r)}
  const evMap=Object.fromEntries(eq.rows.map(x=>[x.gate_id,x.c]));const payBy=new Map();for(const p of payq.rows)if(!payBy.has(p.gate_id))payBy.set(p.gate_id,p)
  const gates=gq.rows.map(g=>({...g,requirements:reqBy.get(g.id)||[],evidence_count:evMap[g.id]||0,payment:payBy.get(g.id)||null}))
  const nextGate=gates.find(g=>g.status!=='released')||null
  const riskRadar=buildRiskRadar(nextGate,sq.rows,gates)
  return{project,gates,payments:payq.rows,passport:passq.rows,riskRadar,summary:{released:gates.filter(g=>g.status==='released').length,blocked:gates.filter(g=>g.status==='blocked').length,pending:gates.filter(g=>g.status==='pending_review').length,passportItems:passq.rows.length,paymentPending:payq.rows.filter(p=>p.status==='pending').length,nextGate}}
}

function buildRiskRadar(gate,safetyOpen,gates){
  if(!gate)return{phase:'Entrega concluída',score:0,level:'baixo',items:[]}
  const phase=gate.phase_name.toLowerCase();const items=[]
  const add=(code,title,severity,why,action,source='Planejamento de etapa')=>items.push({code,title,severity,why,action,source})
  if(phase.includes('fund')){add('excavation','Escavações, taludes e acesso','alta','A etapa pode envolver escavação, circulação de equipamentos e condições variáveis do terreno.','Validar estabilidade, acesso, isolamento e medidas de controle aplicáveis.','Gate de fundações');add('foundation-check','Conferência antes da concretagem','alta','Erros ficam ocultos após a concretagem.','Registrar locação, armaduras, cotas e evidências antes do fechamento.','Qualidade / engenharia')}
  if(phase.includes('estrutura')){add('fall','Trabalho em altura e bordas','critica','A execução estrutural pode expor trabalhadores a quedas em níveis diferentes.','Validar proteção coletiva, acessos, plataformas e demais controles aplicáveis.','SST / etapa');add('pour','Concretagem e armaduras','alta','A correção depois da concretagem pode ser onerosa ou inviável.','Conferir projeto, formas, armaduras e interfaces antes da liberação.','Engenharia')}
  if(phase.includes('cobertura'))add('roof','Cobertura e trabalho em altura','critica','Cobertura tende a concentrar riscos de queda e acesso.','Planejar acesso, proteção contra quedas, isolamento e condição climática antes do início.','SST / cobertura')
  if(phase.includes('instala')){add('hidden','Instalações que ficarão ocultas','alta','Tubulações e eletrodutos podem ficar inacessíveis após o fechamento.','Registrar fotos por ambiente e referências de posição antes de fechar paredes e pisos.','Obra360 PASS');add('electric','Risco elétrico e interferências','alta','Instalações provisórias e definitivas exigem controle e compatibilização.','Verificar condições seguras e compatibilidade das instalações antes da continuidade.','SST / instalações')}
  if(phase.includes('imperme'))add('waterproof','Impermeabilização antes do revestimento','alta','Falhas podem aparecer somente após a entrega e gerar retrabalho relevante.','Registrar preparação, execução e testes aplicáveis antes do revestimento.','Qualidade')
  if(phase.includes('acab'))add('finish','Proteção e retrabalho de acabamento','media','Serviços simultâneos podem danificar itens já concluídos.','Sequenciar frentes, proteger acabamentos e registrar pendências por ambiente.','Planejamento')
  for(const s of safetyOpen.slice(0,3))add(`sst-${s.id}`,s.title,s.severity||'media',s.description||'Existe uma pendência de segurança aberta no sistema.','Resolver ou validar a pendência antes de atividades incompatíveis.',s.standard_ref||'Registro de SST')
  const reqPending=gate.requirements?.filter(r=>r.required&&!['concluido','nao_aplicavel'].includes(r.status)).length||0;if(reqPending)add('requirements',`${reqPending} requisito(s) obrigatório(s) pendente(s)`,'media','O gate ainda possui itens obrigatórios não concluídos.','Revisar e concluir ou justificar a não aplicabilidade antes de liberar a etapa.','Obra360 PASS')
  const weights={baixa:10,media:20,alta:30,critica:45};const raw=items.reduce((s,i)=>s+weights[i.severity],0);const score=Math.min(100,raw);const level=score>=80?'critico':score>=55?'alto':score>=30?'medio':'baixo';return{phase:gate.phase_name,score,level,items}
}

const app=express();app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(cookieParser())
app.get('/api/health',(_q,res)=>res.json({ok:true,product:'Obra360 PASS'}))
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').toLowerCase().trim(),password=String(req.body.password||'');const u=(await pool.query('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'E-mail ou senha inválidos'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.cookie(COOKIE,token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})})
app.post('/api/auth/logout',(_q,res)=>{res.clearCookie(COOKIE);res.json({ok:true})})
app.get('/api/me',auth,async(req,res)=>{const u=(await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[req.user.id])).rows[0];res.json({user:u})})
app.get('/api/projects',auth,async(req,res)=>{const q=['admin','team'].includes(req.user.role)?await pool.query('SELECT * FROM projects ORDER BY updated_at DESC,id DESC'):await pool.query('SELECT p.* FROM projects p JOIN project_members pm ON pm.project_id=p.id WHERE pm.user_id=$1 ORDER BY p.updated_at DESC',[req.user.id]);res.json({projects:q.rows})})
app.post('/api/projects',auth,staff,async(req,res)=>{const{name,city,address,clientName,budget}=req.body;if(!name)return res.status(400).json({error:'Nome da obra é obrigatório'});const c=await pool.connect();try{await c.query('BEGIN');const p=(await c.query(`INSERT INTO projects(name,city,address,client_name,budget,status) VALUES($1,$2,$3,$4,$5,'planejamento') RETURNING *`,[name,city||null,address||null,clientName||null,num(budget)])).rows[0];for(let i=0;i<DEFAULT_PHASES.length;i++)await c.query('INSERT INTO phases(project_id,name,order_index,status) VALUES($1,$2,$3,$4)',[p.id,DEFAULT_PHASES[i],i+1,i===0?'em_andamento':'nao_iniciada']);await c.query(`INSERT INTO project_events(project_id,event_type,title,description,created_by) VALUES($1,'sistema','Obra criada','Estrutura inicial do Obra360 PASS criada. Gates e requisitos ainda precisam de revisão da equipe.',$2)`,[p.id,req.user.id]);await c.query('COMMIT');await seedGates(p.id);res.status(201).json({project:p})}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'Não foi possível criar a obra'})}finally{c.release()}})
app.get('/api/pass/projects/:id',auth,async(req,res)=>{const id=Number(req.params.id);if(!(await access(req.user,id)))return res.status(403).json({error:'Sem acesso'});const b=await getPass(id);if(!b)return res.status(404).json({error:'Obra não encontrada'});res.json(b)})
app.patch('/api/pass/projects/:projectId/gates/:gateId',auth,staff,async(req,res)=>{const{status,technicalScore,notes}=req.body;const gid=Number(req.params.gateId),pid=Number(req.params.projectId);const gate=(await pool.query('SELECT * FROM phase_gates WHERE id=$1 AND project_id=$2',[gid,pid])).rows[0];if(!gate)return res.status(404).json({error:'Gate não encontrado'});if(status==='released'){const pending=(await pool.query(`SELECT count(*)::int c FROM gate_requirements WHERE gate_id=$1 AND required=true AND status NOT IN ('concluido','nao_aplicavel')`,[gid])).rows[0].c;if(pending>0)return res.status(409).json({error:`Existem ${pending} requisito(s) obrigatório(s) pendente(s).`});const previous=(await pool.query(`SELECT count(*)::int c FROM phase_gates WHERE project_id=$1 AND order_index<$2 AND status<>'released'`,[pid,gate.order_index])).rows[0].c;if(previous>0)return res.status(409).json({error:'Existe etapa anterior ainda não liberada.'})}const q=await pool.query(`UPDATE phase_gates SET status=COALESCE($1,status),technical_score=COALESCE($2,technical_score),notes=COALESCE($3,notes),released_at=CASE WHEN $1='released' THEN now() WHEN $1 IS NULL THEN released_at ELSE NULL END,released_by=CASE WHEN $1='released' THEN $4 WHEN $1 IS NULL THEN released_by ELSE NULL END,updated_at=now() WHERE id=$5 RETURNING *`,[status||null,technicalScore===''?null:technicalScore,notes||null,req.user.id,gid]);if(status==='released')await pool.query(`INSERT INTO project_events(project_id,event_type,title,description,created_by) VALUES($1,'gate',$2,$3,$4)`,[pid,`Gate liberado: ${gate.phase_name}`,'Etapa registrada como tecnicamente liberada no Obra360 PASS.',req.user.id]);res.json({gate:q.rows[0]})})
app.patch('/api/pass/projects/:projectId/requirements/:requirementId',auth,staff,async(req,res)=>{const{status,notes}=req.body;if(!['pendente','concluido','nao_aplicavel'].includes(status))return res.status(400).json({error:'Status inválido'});const q=await pool.query(`UPDATE gate_requirements r SET status=$1,notes=COALESCE($2,r.notes),updated_at=now() FROM phase_gates g WHERE r.id=$3 AND r.gate_id=g.id AND g.project_id=$4 RETURNING r.*`,[status,notes||null,req.params.requirementId,req.params.projectId]);res.json({requirement:q.rows[0]})})
app.post('/api/pass/projects/:id/evidence',auth,staff,async(req,res)=>{const{gateId,requirementId,evidenceType,title,description,url}=req.body;if(!gateId||!title)return res.status(400).json({error:'Gate e título são obrigatórios'});const q=await pool.query(`INSERT INTO gate_evidence(project_id,gate_id,requirement_id,evidence_type,title,description,url,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.params.id,gateId,requirementId||null,evidenceType||'photo',title,description||null,url||null,req.user.id]);await pool.query(`INSERT INTO project_events(project_id,event_type,title,description,created_by) VALUES($1,'evidencia',$2,$3,$4)`,[req.params.id,`Evidência registrada: ${title}`,description||'Registro vinculado a um gate da obra.',req.user.id]);res.status(201).json({evidence:q.rows[0]})})
app.post('/api/pass/projects/:id/payments',auth,staff,async(req,res)=>{const{gateId,description,claimedAmount,validatedAmount,recommendation,reason}=req.body;if(!description)return res.status(400).json({error:'Descrição obrigatória'});const q=await pool.query(`INSERT INTO payment_releases(project_id,gate_id,description,claimed_amount,validated_amount,recommendation,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.params.id,gateId||null,description,num(claimedAmount),num(validatedAmount),recommendation||'hold',reason||null,req.user.id]);res.status(201).json({payment:q.rows[0]})})
app.patch('/api/pass/projects/:projectId/payments/:id',auth,async(req,res)=>{const pid=Number(req.params.projectId);if(!(await access(req.user,pid)))return res.status(403).json({error:'Sem acesso'});const status=req.body.status;if(!['approved','rejected'].includes(status))return res.status(400).json({error:'Status inválido'});const q=await pool.query(`UPDATE payment_releases SET status=$1,decided_at=now(),decided_by=$2 WHERE id=$3 AND project_id=$4 RETURNING *`,[status,req.user.id,req.params.id,pid]);if(!q.rows[0])return res.status(404).json({error:'Medição não encontrada'});await pool.query(`INSERT INTO project_events(project_id,event_type,title,description,created_by) VALUES($1,'pagamento',$2,$3,$4)`,[pid,`${status==='approved'?'Pagamento liberado':'Pagamento não liberado'}: ${q.rows[0].description}`,`Valor validado: ${q.rows[0].validated_amount}`,req.user.id]);res.json({payment:q.rows[0]})})
app.post('/api/pass/projects/:id/passport',auth,staff,async(req,res)=>{const{systemType,zone,title,description,photoUrl,heightCm,depthCm,warrantyUntil,supplier}=req.body;if(!title||!systemType)return res.status(400).json({error:'Sistema e título são obrigatórios'});const q=await pool.query(`INSERT INTO passport_items(project_id,system_type,zone,title,description,photo_url,height_cm,depth_cm,warranty_until,supplier,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.params.id,systemType,zone||null,title,description||null,photoUrl||null,heightCm||null,depthCm||null,warrantyUntil||null,supplier||null,req.user.id]);res.status(201).json({item:q.rows[0]})})
app.get('/api/public/pass/:id',async(req,res)=>{const id=Number(req.params.id);await seedGates(id);const p=(await pool.query('SELECT id,name,city,status,progress,updated_at FROM projects WHERE id=$1',[id])).rows[0];if(!p)return res.status(404).json({error:'Obra não encontrada'});const g=(await pool.query('SELECT phase_name,status,released_at FROM phase_gates WHERE project_id=$1 ORDER BY order_index',[id])).rows;res.json({project:p,verification:{released:g.filter(x=>x.status==='released').length,total:g.length,current:g.find(x=>x.status!=='released')?.phase_name||'Concluída',lastRelease:g.filter(x=>x.released_at).at(-1)?.released_at||null},gates:g})})

function groundedAnswer(b,q){const s=q.toLowerCase(),next=b.summary.nextGate,pendingReq=next?.requirements.filter(r=>r.required&&!['concluido','nao_aplicavel'].includes(r.status))||[],pendingPay=b.payments.filter(p=>p.status==='pending');if(/pagamento|pagar|medi[cç][aã]o/.test(s)){if(!pendingPay.length)return'Não há liberação financeira pendente registrada.';const p=pendingPay[0];return`A medição pendente “${p.description}” solicita ${num(p.claimed_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} e tem ${num(p.validated_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} como valor validado. Recomendação registrada: ${p.recommendation}. ${p.reason||''}`};if(/pr[oó]xima etapa|liberar|avan[cç]ar/.test(s))return next?pendingReq.length?`A próxima etapa é ${next.phase_name}. Ainda existem ${pendingReq.length} requisito(s) obrigatório(s) pendente(s): ${pendingReq.slice(0,5).map(r=>r.title).join('; ')}.`:`A próxima etapa é ${next.phase_name}. Os requisitos obrigatórios cadastrados estão concluídos, mas a liberação final depende do profissional responsável.`:'Todos os gates cadastrados estão liberados.';if(/tubula|el[eé]tric|onde passa|parede|hidraul/.test(s)){const hits=b.passport.filter(i=>/hidraul|eletric|gas/.test(i.system_type)).slice(0,6);return hits.length?`Há ${hits.length} registro(s) relevantes no passaporte: ${hits.map(i=>`${i.title} — ${i.zone||'sem ambiente informado'}${i.height_cm?`, altura ${i.height_cm} cm`:''}`).join('; ')}. Confirme no local antes de perfurar ou intervir.`:'Não encontrei evidência de instalações ocultas suficiente no passaporte. Não é seguro inferir por ausência de registro.'}if(/garantia|manuten/.test(s)){const hits=b.passport.filter(i=>i.warranty_until||i.system_type==='garantia');return hits.length?`Garantias registradas: ${hits.map(i=>`${i.title}${i.warranty_until?` até ${i.warranty_until}`:''}`).join('; ')}.`:'Não há garantias cadastradas no passaporte.'}if(/risco|seguran|amanh[aã]|pr[oó]xima atividade/.test(s))return`O Radar da próxima etapa está em ${b.riskRadar.score}/100 (${b.riskRadar.level}) para ${b.riskRadar.phase}. Principais alertas: ${b.riskRadar.items.slice(0,5).map(i=>i.title).join('; ')||'nenhum alerta calculado'}.`;return`Resumo verificável: ${b.summary.released}/${b.gates.length} gates liberados, ${b.summary.paymentPending} medição(ões) pendente(s), ${b.summary.passportItems} item(ns) no passaporte técnico e radar ${b.riskRadar.score}/100 para a próxima etapa.`}
app.post('/api/pass/projects/:id/ai',auth,async(req,res)=>{const id=Number(req.params.id);if(!(await access(req.user,id)))return res.status(403).json({error:'Sem acesso'});const question=String(req.body.question||'').trim();if(!question)return res.status(400).json({error:'Pergunta vazia'});const b=await getPass(id);if(!OPENAI_API_KEY)return res.json({answer:groundedAnswer(b,question),mode:'grounded'});try{const context=JSON.stringify({project:b.project,gates:b.gates,payments:b.payments,passport:b.passport,riskRadar:b.riskRadar});const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,instructions:'Você é a Obra IA do Obra360 PASS. Responda em português do Brasil apenas com base nos registros fornecidos. Nunca invente evidência, medição, posição de tubulação, norma aplicável, liberação técnica ou fato ausente. Distingua registro do sistema de recomendação geral. Para decisões técnicas ou de SST, a validação final é do profissional responsável. Seja objetivo.',input:`REGISTROS:\n${context}\n\nPERGUNTA:\n${question}`,max_output_tokens:800})});if(!r.ok)throw new Error('IA indisponível');const d=await r.json();let answer=d.output_text;if(!answer&&Array.isArray(d.output))answer=d.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');res.json({answer:answer||groundedAnswer(b,question),mode:answer?'ai':'grounded'})}catch(e){console.error(e);res.json({answer:groundedAnswer(b,question),mode:'grounded'})}})

const dist=path.join(__dirname,'dist');app.use(express.static(dist));app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(path.join(dist,'index.html'))})
migrate().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Obra360 PASS ativo na porta ${PORT}`))).catch(e=>{console.error(e);process.exit(1)})
