import express from 'express'
import cookieParser from 'cookie-parser'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import pg from 'pg'
import path from 'path'
import { fileURLToPath } from 'url'
import { STAGES, buildWorkflow } from './workflow-v3.mjs'

const { Pool } = pg
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PORT = Number(process.env.PORT || 10000)
const DATABASE_URL = process.env.DATABASE_URL
const JWT_SECRET = process.env.JWT_SECRET || 'change-me-in-production'
const COOKIE = 'obra360_session'
const OPENAI_API_KEY = process.env.OPENAI_API_KEY
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-5.6-terra'
if (!DATABASE_URL) { console.error('DATABASE_URL ausente'); process.exit(1) }
const pool = new Pool({ connectionString:DATABASE_URL, ssl:DATABASE_URL.includes('localhost')||DATABASE_URL.includes('127.0.0.1')?false:{rejectUnauthorized:false} })

async function migrate(){
  const c=await pool.connect();try{await c.query('BEGIN');await c.query(`
    CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'client',created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS projects(id SERIAL PRIMARY KEY,name TEXT NOT NULL,city TEXT,address TEXT,client_name TEXT,status TEXT NOT NULL DEFAULT 'planejamento',start_date DATE,planned_end_date DATE,budget NUMERIC(14,2) DEFAULT 0,committed NUMERIC(14,2) DEFAULT 0,spent NUMERIC(14,2) DEFAULT 0,progress NUMERIC(5,2) DEFAULT 0,planned_progress NUMERIC(5,2) DEFAULT 0,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS project_members(project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,member_role TEXT DEFAULT 'client',PRIMARY KEY(project_id,user_id));
    CREATE TABLE IF NOT EXISTS os_profiles(project_id INTEGER PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,profile JSONB NOT NULL DEFAULT '{}'::jsonb,workflow_version TEXT NOT NULL DEFAULT '2026.09-v3',updated_at TIMESTAMPTZ DEFAULT now(),updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL);
    CREATE TABLE IF NOT EXISTS os_tasks(id SERIAL PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,code TEXT NOT NULL,stage_key TEXT NOT NULL,discipline TEXT NOT NULL,title TEXT NOT NULL,detail TEXT,role TEXT,required BOOLEAN DEFAULT true,priority TEXT DEFAULT 'normal',status TEXT NOT NULL DEFAULT 'pending',client_action BOOLEAN DEFAULT false,source_label TEXT,source_url TEXT,legal_note TEXT,task_order INTEGER DEFAULT 0,is_custom BOOLEAN DEFAULT false,metadata JSONB DEFAULT '{}'::jsonb,completed_at TIMESTAMPTZ,completed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(project_id,code));
    CREATE TABLE IF NOT EXISTS os_events(id SERIAL PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,event_type TEXT NOT NULL DEFAULT 'task',title TEXT NOT NULL,description TEXT,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS os_custom_stages(id SERIAL PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,stage_key TEXT NOT NULL,title TEXT NOT NULL,summary TEXT,stage_order NUMERIC(8,2) NOT NULL DEFAULT 99,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(project_id,stage_key));
    CREATE TABLE IF NOT EXISTS os_photos(id SERIAL PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,data_url TEXT NOT NULL,caption TEXT,stage_key TEXT,task_id INTEGER REFERENCES os_tasks(id) ON DELETE SET NULL,ai_summary TEXT,ai_confidence NUMERIC(5,2),ai_tags JSONB DEFAULT '[]'::jsonb,ai_safety JSONB DEFAULT '[]'::jsonb,uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
    CREATE TABLE IF NOT EXISTS passport_items(id SERIAL PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,system_type TEXT NOT NULL,zone TEXT,title TEXT NOT NULL,description TEXT,photo_url TEXT,warranty_until DATE,supplier TEXT,metadata JSONB DEFAULT '{}'::jsonb,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT now());
    CREATE INDEX IF NOT EXISTS idx_os_tasks_project_stage ON os_tasks(project_id,stage_key,task_order);
    CREATE INDEX IF NOT EXISTS idx_os_photos_project ON os_photos(project_id,created_at DESC);
  `);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
  const email=process.env.ADMIN_EMAIL,password=process.env.ADMIN_PASSWORD,name=process.env.ADMIN_NAME||'Equipe Obra360'
  if(email&&password){const hash=await bcrypt.hash(password,12);await pool.query(`INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,'admin') ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,role='admin'`,[name,email.toLowerCase(),hash])}
}

function auth(req,res,next){const token=req.cookies[COOKIE];if(!token)return res.status(401).json({error:'Não autenticado'});try{req.user=jwt.verify(token,JWT_SECRET);next()}catch{return res.status(401).json({error:'Sessão expirada'})}}
function staff(req,res,next){if(!['admin','team'].includes(req.user?.role))return res.status(403).json({error:'Acesso restrito à equipe técnica'});next()}
async function canAccess(user,id){if(['admin','team'].includes(user.role))return true;const q=await pool.query('SELECT 1 FROM project_members WHERE project_id=$1 AND user_id=$2',[id,user.id]);return q.rowCount>0}

async function syncWorkflow(projectId,profile,userId){
  const generated=buildWorkflow(profile), c=await pool.connect();try{await c.query('BEGIN');await c.query(`INSERT INTO os_profiles(project_id,profile,workflow_version,updated_by) VALUES($1,$2,'2026.09-v3',$3) ON CONFLICT(project_id) DO UPDATE SET profile=EXCLUDED.profile,workflow_version='2026.09-v3',updated_at=now(),updated_by=EXCLUDED.updated_by`,[projectId,profile,userId]);const codes=[];for(const t of generated){codes.push(t.code);await c.query(`INSERT INTO os_tasks(project_id,code,stage_key,discipline,title,detail,role,required,priority,client_action,source_label,source_url,legal_note,task_order,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(project_id,code) DO UPDATE SET stage_key=EXCLUDED.stage_key,discipline=EXCLUDED.discipline,title=EXCLUDED.title,detail=EXCLUDED.detail,role=EXCLUDED.role,required=EXCLUDED.required,priority=EXCLUDED.priority,client_action=EXCLUDED.client_action,task_order=EXCLUDED.task_order,metadata=EXCLUDED.metadata,updated_at=now()`,[projectId,t.code,t.stage,t.discipline,t.title,t.detail,t.role,t.required,t.priority,t.client_action,t.source_label,t.source_url,t.legal_note,t.task_order,t.metadata])}if(codes.length)await c.query(`DELETE FROM os_tasks WHERE project_id=$1 AND is_custom=false AND NOT(code=ANY($2::text[]))`,[projectId,codes]);await c.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'workflow','Roteiro automático atualizado',$2,$3)`,[projectId,`${generated.length} ações foram recalculadas a partir do perfil da obra.`,userId]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}
}

async function getBundle(projectId){
  const [p,prof,tq,evq,passq,csq,photosq]=await Promise.all([
    pool.query('SELECT * FROM projects WHERE id=$1',[projectId]),pool.query('SELECT * FROM os_profiles WHERE project_id=$1',[projectId]),pool.query('SELECT t.*,u.name completed_by_name FROM os_tasks t LEFT JOIN users u ON u.id=t.completed_by WHERE t.project_id=$1 ORDER BY task_order,id',[projectId]),pool.query('SELECT e.*,u.name author_name FROM os_events e LEFT JOIN users u ON u.id=e.created_by WHERE e.project_id=$1 ORDER BY e.created_at DESC LIMIT 80',[projectId]),pool.query('SELECT * FROM passport_items WHERE project_id=$1 ORDER BY created_at DESC',[projectId]),pool.query('SELECT * FROM os_custom_stages WHERE project_id=$1 ORDER BY stage_order,id',[projectId]),pool.query(`SELECT p.*,u.name uploaded_by_name,t.title task_title FROM os_photos p LEFT JOIN users u ON u.id=p.uploaded_by LEFT JOIN os_tasks t ON t.id=p.task_id WHERE p.project_id=$1 ORDER BY p.created_at DESC LIMIT 100`,[projectId])
  ])
  if(!p.rows[0])return null
  const tasks=tq.rows, customStages=csq.rows
  const stageDefs=[...STAGES.map((s,i)=>({num:s[0],key:s[1],title:s[2],summary:s[3],order:i})),...customStages.map((s,i)=>({num:`+${i+1}`,key:s.stage_key,title:s.title,summary:s.summary||'Etapa personalizada da obra.',order:Number(s.stage_order)}))].sort((a,b)=>a.order-b.order)
  const stages=stageDefs.map(s=>{const list=tasks.filter(t=>t.stage_key===s.key),active=list.filter(t=>t.status!=='na'),done=active.filter(t=>t.status==='done').length;return {...s,total:list.length,applicable:active.length,done,progress:active.length?Math.round(done/active.length*100):0}}).filter(s=>s.total>0||customStages.some(c=>c.stage_key===s.key))
  const applicable=tasks.filter(t=>t.status!=='na'),done=tasks.filter(t=>t.status==='done').length,progress=applicable.length?Math.round(done/applicable.length*100):0
  const disciplines={};for(const t of tasks){if(t.status==='na')continue;disciplines[t.discipline]??={total:0,done:0};disciplines[t.discipline].total++;if(t.status==='done')disciplines[t.discipline].done++}
  return {project:p.rows[0],profile:prof.rows[0]?.profile||null,workflowVersion:prof.rows[0]?.workflow_version||null,tasks,events:evq.rows,passport:passq.rows,photos:photosq.rows,stages,disciplines,summary:{total:tasks.length,done,na:tasks.filter(t=>t.status==='na').length,applicable:applicable.length,progress,nextTask:tasks.find(t=>t.status==='pending'&&t.required)||tasks.find(t=>t.status==='pending')||null}}
}

const app=express();app.disable('x-powered-by');app.use(express.json({limit:'8mb'}));app.use(cookieParser())
app.get('/api/health',(_req,res)=>res.json({ok:true,product:'VIÇO',service:'obra360-portal'}))
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),q=await pool.query('SELECT * FROM users WHERE email=$1',[email]),u=q.rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'E-mail ou senha inválidos'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.cookie(COOKIE,token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role}})})
app.post('/api/auth/logout',(_req,res)=>{res.clearCookie(COOKIE);res.json({ok:true})})
app.get('/api/me',auth,async(req,res)=>{const q=await pool.query('SELECT id,name,email,role FROM users WHERE id=$1',[req.user.id]);res.json({user:q.rows[0]})})
app.get('/api/projects',auth,async(req,res)=>{let q;if(['admin','team'].includes(req.user.role))q=await pool.query('SELECT * FROM projects ORDER BY updated_at DESC,id DESC');else q=await pool.query('SELECT p.* FROM projects p JOIN project_members pm ON pm.project_id=p.id WHERE pm.user_id=$1 ORDER BY p.updated_at DESC',[req.user.id]);res.json({projects:q.rows})})
app.post('/api/projects',auth,staff,async(req,res)=>{const{name,city,address,clientName,budget=0}=req.body;if(!name)return res.status(400).json({error:'Nome da obra obrigatório'});const q=await pool.query(`INSERT INTO projects(name,city,address,client_name,budget,status) VALUES($1,$2,$3,$4,$5,'planejamento') RETURNING *`,[name,city||null,address||null,clientName||null,Number(budget)||0]);res.status(201).json({project:q.rows[0]})})

app.get('/api/os/projects/:id',auth,async(req,res)=>{const id=Number(req.params.id);if(!(await canAccess(req.user,id)))return res.status(403).json({error:'Sem acesso'});const b=await getBundle(id);if(!b)return res.status(404).json({error:'Obra não encontrada'});res.json(b)})
app.put('/api/os/projects/:id/profile',auth,staff,async(req,res)=>{const id=Number(req.params.id),pq=await pool.query('SELECT * FROM projects WHERE id=$1',[id]);if(!pq.rows[0])return res.status(404).json({error:'Obra não encontrada'});const profile={...req.body,city:req.body.city||pq.rows[0].city||'',state:req.body.state||'MG'};await syncWorkflow(id,profile,req.user.id);await pool.query('UPDATE projects SET city=COALESCE($1,city),updated_at=now() WHERE id=$2',[profile.city||null,id]);res.json({ok:true})})
app.patch('/api/os/projects/:projectId/tasks/:taskId',auth,async(req,res)=>{const projectId=Number(req.params.projectId),taskId=Number(req.params.taskId);if(!(await canAccess(req.user,projectId)))return res.status(403).json({error:'Sem acesso'});const q=await pool.query('SELECT * FROM os_tasks WHERE id=$1 AND project_id=$2',[taskId,projectId]),t=q.rows[0];if(!t)return res.status(404).json({error:'Item não encontrado'});const isStaff=['admin','team'].includes(req.user.role);if(!isStaff&&!t.client_action)return res.status(403).json({error:'Este item exige validação da equipe técnica'});const status=req.body.status;if(!['pending','done','na'].includes(status))return res.status(400).json({error:'Status inválido'});const u=await pool.query(`UPDATE os_tasks SET status=$1,completed_at=CASE WHEN $1='done' THEN now() ELSE NULL END,completed_by=CASE WHEN $1='done' THEN $2 ELSE NULL END,updated_at=now() WHERE id=$3 RETURNING *`,[status,req.user.id,taskId]);await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'task',$2,$3,$4)`,[projectId,`${status==='done'?'Concluído':status==='na'?'Não aplicável':'Reaberto'}: ${t.title}`,`Disciplina: ${t.discipline}.`,req.user.id]);res.json({task:u.rows[0]})})
app.post('/api/os/projects/:id/tasks',auth,staff,async(req,res)=>{const id=Number(req.params.id),{stageKey='planejamento',discipline='gestao',title,detail='',role='equipe'}=req.body;if(!title)return res.status(400).json({error:'Título obrigatório'});const code=`custom_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,max=await pool.query('SELECT COALESCE(MAX(task_order),0)+1 n FROM os_tasks WHERE project_id=$1',[id]),q=await pool.query(`INSERT INTO os_tasks(project_id,code,stage_key,discipline,title,detail,role,required,priority,task_order,is_custom) VALUES($1,$2,$3,$4,$5,$6,$7,false,'normal',$8,true) RETURNING *`,[id,code,stageKey,discipline,title,detail,role,max.rows[0].n]);res.status(201).json({task:q.rows[0]})})
app.post('/api/os/projects/:id/stages',auth,staff,async(req,res)=>{const id=Number(req.params.id),title=String(req.body.title||'').trim(),summary=String(req.body.summary||'').trim();if(!title)return res.status(400).json({error:'Nome da etapa obrigatório'});const key=`custom_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,order=Number(req.body.stageOrder)||99,q=await pool.query(`INSERT INTO os_custom_stages(project_id,stage_key,title,summary,stage_order,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[id,key,title,summary,order,req.user.id]);await pool.query(`INSERT INTO os_events(project_id,event_type,title,description,created_by) VALUES($1,'stage',$2,$3,$4)`,[id,`Etapa adicionada: ${title}`,summary||'Etapa personalizada.',req.user.id]);res.status(201).json({stage:q.rows[0]})})

app.post('/api/os/projects/:id/photos/analyze',auth,async(req,res)=>{const projectId=Number(req.params.id);if(!(await canAccess(req.user,projectId)))return res.status(403).json({error:'Sem acesso'});const dataUrl=String(req.body.dataUrl||''),caption=String(req.body.caption||'').trim();if(!dataUrl.startsWith('data:image/'))return res.status(400).json({error:'Imagem inválida'});const tq=await pool.query(`SELECT id,title,detail,stage_key,discipline,status,client_action FROM os_tasks WHERE project_id=$1 AND status='pending' ORDER BY task_order LIMIT 140`,[projectId]);const tasks=tq.rows;let result={summary:caption||'Foto adicionada à obra.',taskId:null,stageKey:null,confidence:0,tags:[],safety:[]};
  if(OPENAI_API_KEY){try{const list=tasks.map(t=>`${t.id}|${t.stage_key}|${t.discipline}|${t.title}`).join('\n');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,instructions:'Você analisa uma foto de obra. Use apenas o que é visível. Escolha no máximo uma tarefa da lista que melhor corresponde à foto. Não declare serviço concluído; apenas sugira classificação. Aponte riscos visuais somente quando realmente visíveis. Responda SOMENTE JSON válido com: summary, taskId (number|null), stageKey (string|null), confidence (0-100), tags (array strings), safety (array strings).',input:[{role:'user',content:[{type:'input_text',text:`Legenda opcional: ${caption||'sem legenda'}\nTarefas pendentes:\n${list}`},{type:'input_image',image_url:dataUrl}]}],max_output_tokens:500})});if(r.ok){const d=await r.json();let text=d.output_text||'';if(!text&&Array.isArray(d.output))text=d.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('');const m=text.match(/\{[\s\S]*\}/);if(m){const parsed=JSON.parse(m[0]);const valid=tasks.find(t=>t.id===Number(parsed.taskId));result={summary:String(parsed.summary||caption||'Foto da obra.'),taskId:valid?.id||null,stageKey:valid?.stage_key||parsed.stageKey||null,confidence:Math.max(0,Math.min(100,Number(parsed.confidence)||0)),tags:Array.isArray(parsed.tags)?parsed.tags.slice(0,8):[],safety:Array.isArray(parsed.safety)?parsed.safety.slice(0,6):[]}}}}catch(e){console.error('photo-ai',e)}}
  if(!result.taskId&&caption){const words=caption.toLowerCase().split(/\W+/).filter(w=>w.length>3);let best=null,bestScore=0;for(const t of tasks){const hay=(t.title+' '+(t.detail||'')+' '+t.discipline).toLowerCase();const score=words.filter(w=>hay.includes(w)).length;if(score>bestScore){best=t;bestScore=score}}if(best){result.taskId=best.id;result.stageKey=best.stage_key;result.confidence=Math.min(75,30+bestScore*12)}}
  const ins=await pool.query(`INSERT INTO os_photos(project_id,data_url,caption,stage_key,task_id,ai_summary,ai_confidence,ai_tags,ai_safety,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[projectId,dataUrl,caption||null,result.stageKey,result.taskId,result.summary,result.confidence,result.tags,result.safety,req.user.id]);res.status(201).json({photo:ins.rows[0],analysis:result})})
app.patch('/api/os/projects/:projectId/photos/:photoId/link',auth,async(req,res)=>{const projectId=Number(req.params.projectId),photoId=Number(req.params.photoId);if(!(await canAccess(req.user,projectId)))return res.status(403).json({error:'Sem acesso'});const taskId=Number(req.body.taskId)||null;let task=null;if(taskId){const q=await pool.query('SELECT * FROM os_tasks WHERE id=$1 AND project_id=$2',[taskId,projectId]);task=q.rows[0];if(!task)return res.status(404).json({error:'Tarefa não encontrada'})}await pool.query('UPDATE os_photos SET task_id=$1,stage_key=$2 WHERE id=$3 AND project_id=$4',[taskId,task?.stage_key||null,photoId,projectId]);let marked=false;if(req.body.markDone&&task){const isStaff=['admin','team'].includes(req.user.role);if(isStaff||task.client_action){await pool.query(`UPDATE os_tasks SET status='done',completed_at=now(),completed_by=$1,updated_at=now() WHERE id=$2`,[req.user.id,task.id]);marked=true}}res.json({ok:true,marked,needsValidation:!!task&&!marked&&!!req.body.markDone})})
app.post('/api/os/projects/:id/photos/task/:taskId',auth,async(req,res)=>{const projectId=Number(req.params.id),taskId=Number(req.params.taskId);if(!(await canAccess(req.user,projectId)))return res.status(403).json({error:'Sem acesso'});const dataUrl=String(req.body.dataUrl||'');if(!dataUrl.startsWith('data:image/'))return res.status(400).json({error:'Imagem inválida'});const tq=await pool.query('SELECT * FROM os_tasks WHERE id=$1 AND project_id=$2',[taskId,projectId]),task=tq.rows[0];if(!task)return res.status(404).json({error:'Item não encontrado'});const q=await pool.query(`INSERT INTO os_photos(project_id,data_url,caption,stage_key,task_id,ai_summary,ai_confidence,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,100,$7) RETURNING *`,[projectId,dataUrl,req.body.caption||null,task.stage_key,task.id,`Foto vinculada a: ${task.title}`,req.user.id]);res.status(201).json({photo:q.rows[0]})})
app.delete('/api/os/projects/:projectId/photos/:photoId',auth,staff,async(req,res)=>{await pool.query('DELETE FROM os_photos WHERE id=$1 AND project_id=$2',[req.params.photoId,req.params.projectId]);res.json({ok:true})})

app.post('/api/os/projects/:id/passport',auth,staff,async(req,res)=>{const id=Number(req.params.id),{systemType='geral',zone='',title,description='',photoUrl='',warrantyUntil,supplier=''}=req.body;if(!title)return res.status(400).json({error:'Título obrigatório'});const q=await pool.query(`INSERT INTO passport_items(project_id,system_type,zone,title,description,photo_url,warranty_until,supplier,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,systemType,zone,title,description,photoUrl,warrantyUntil||null,supplier,req.user.id]);res.status(201).json({item:q.rows[0]})})
app.post('/api/os/projects/:id/users',auth,staff,async(req,res)=>{const id=Number(req.params.id),{name,email,password,role='client'}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Nome, e-mail e senha são obrigatórios'});const hash=await bcrypt.hash(password,12),q=await pool.query(`INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name RETURNING id,name,email,role`,[name,email.toLowerCase(),hash,role==='team'?'team':'client']),u=q.rows[0];await pool.query(`INSERT INTO project_members(project_id,user_id,member_role) VALUES($1,$2,$3) ON CONFLICT(project_id,user_id) DO UPDATE SET member_role=EXCLUDED.member_role`,[id,u.id,role]);res.status(201).json({user:u})})

app.post('/api/os/projects/:id/ai',auth,async(req,res)=>{const id=Number(req.params.id);if(!(await canAccess(req.user,id)))return res.status(403).json({error:'Sem acesso'});const q=String(req.body.question||'').trim();if(!q)return res.status(400).json({error:'Pergunta vazia'});const b=await getBundle(id),pending=b.tasks.filter(t=>t.status==='pending'),low=q.toLowerCase();let fallback;if(/foto|imagem|registro visual/.test(low))fallback=`Há ${b.photos.length} foto(s) registradas. As mais recentes estão ligadas a: ${b.photos.slice(0,5).map(p=>p.task_title||p.ai_summary||'registro sem tarefa').join('; ')}.`;else if(/prefeitura|alvar|habite|regulariz/.test(low))fallback=`Pendências de Prefeitura/regularização: ${pending.filter(t=>['prefeitura','federal'].includes(t.discipline)).slice(0,8).map(t=>t.title).join('; ')||'nenhuma registrada'}.`;else if(/arquitet|projeto/.test(low))fallback=`Pendências de arquitetura/projetos: ${pending.filter(t=>['arquitetura','cliente'].includes(t.discipline)||['arquitetura','complementares'].includes(t.stage_key)).slice(0,8).map(t=>t.title).join('; ')||'nenhuma registrada'}.`;else if(/seguran|sst|pgr|nr/.test(low))fallback=`Pendências de SST: ${pending.filter(t=>t.discipline==='sst').slice(0,8).map(t=>t.title).join('; ')||'nenhuma registrada'}.`;else fallback=`A obra está ${b.summary.progress}% concluída no roteiro. Próxima ação: ${b.summary.nextTask?.title||'nenhuma pendência registrada'}.`
  if(!OPENAI_API_KEY)return res.json({answer:fallback,mode:'grounded'});try{const context=JSON.stringify({project:b.project,profile:b.profile,summary:b.summary,pending:pending.slice(0,45),photos:b.photos.slice(0,20).map(p=>({caption:p.caption,summary:p.ai_summary,task:p.task_title,stage:p.stage_key,safety:p.ai_safety})),events:b.events.slice(0,20),passport:b.passport.slice(0,20)}),r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,instructions:'Você é a Obra IA. Responda em português, usando primeiro os dados registrados. Não invente exigências, conclusões técnicas ou fatos visuais. Se o dado não existe, diga. Diferencie sugestão de validação profissional.',input:`CONTEXTO\n${context}\n\nPERGUNTA\n${q}`,max_output_tokens:800})});if(!r.ok)throw new Error('falha IA');const d=await r.json();let answer=d.output_text||'';if(!answer&&Array.isArray(d.output))answer=d.output.flatMap(o=>o.content||[]).filter(c=>c.type==='output_text').map(c=>c.text).join('\n');res.json({answer:answer||fallback,mode:answer?'ai':'grounded'})}catch{res.json({answer:fallback,mode:'grounded'})}})

const dist=path.join(__dirname,'dist');app.use(express.static(dist));app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(path.join(dist,'index.html'))})
migrate().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Núcleo VIÇO ativo na porta ${PORT}`))).catch(e=>{console.error('Falha inicial',e);process.exit(1)})
